const MOVE_SFX_MAP = {
    'Absorb': ['music/battle_anims/PRSFX- Absorb1.wav', 'music/battle_anims/PRSFX- Absorb2.wav'],
    'Accelerock': ['music/battle_anims/PRSFX- Accelerock1.wav', 'music/battle_anims/PRSFX- Accelerock2.wav', 'music/battle_anims/PRSFX- Accelerock3.wav'],
    'Acid': ['music/battle_anims/PRSFX- Acid.wav'],
    'Acid Armor': ['music/battle_anims/PRSFX- Acid Armor1.wav', 'music/battle_anims/PRSFX- Acid Armor2.wav'],
    'Acid Spray': ['music/battle_anims/PRSFX- Acid Spray.wav'],
    'Acrobatics': ['music/battle_anims/PRSFX- Acrobatics1.wav', 'music/battle_anims/PRSFX- Acrobatics2.wav', 'music/battle_anims/PRSFX- Acrobatics3.wav'],
    'Acupressure': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Aerial Ace': ['music/battle_anims/PRSFX- Aerial Ace.wav'],
    'Aeroblast': ['music/battle_anims/PRSFX- Aeroblast.wav'],
    'After You': ['music/battle_anims/PRSFX- After You1.wav', 'music/battle_anims/PRSFX- After You2.wav'],
    'Agility': ['music/battle_anims/PRSFX- Agility.wav'],
    'Air Cutter': ['music/battle_anims/PRSFX- Air Cutter1.wav', 'music/battle_anims/PRSFX- Air Cutter2.wav'],
    'Air Slash': ['music/battle_anims/PRSFX- Air Slash1.wav', 'music/battle_anims/PRSFX- Air Slash2.wav', 'music/battle_anims/PRSFX- Air Slash3.wav'],
    'All Out Pummeling': ['music/battle_anims/PRSFX- All Out Pummeling1.wav', 'music/battle_anims/PRSFX- All Out Pummeling2.wav', 'music/battle_anims/PRSFX- All Out Pummeling3.wav'],
    'Ally Switch': ['music/battle_anims/PRSFX- Ally Switch.wav'],
    'Amnesia': ['music/battle_anims/PRSFX- Amnesia.wav'],
    'Anchor Shot': ['music/battle_anims/PRSFX- Anchor Shot.wav', 'music/battle_anims/PRSFX- Anchor Shot1.wav', 'music/battle_anims/PRSFX- Anchor Shot2.wav'],
    'Ancient Power': ['music/battle_anims/PRSFX- Ancient Power1.wav', 'music/battle_anims/PRSFX- Ancient Power2.wav'],
    'Aqua Jet': ['music/battle_anims/PRSFX- Aqua Jet.wav'],
    'Aqua Ring': ['music/battle_anims/PRSFX- Aqua Ring1.wav', 'music/battle_anims/PRSFX- Aqua Ring2.wav'],
    'Aqua Tail': ['music/battle_anims/PRSFX- Aqua Tail.wav'],
    'Arm Thrust': ['music/battle_anims/PRSFX- Arm Thrust.wav'],
    'Aromatherapy': ['music/battle_anims/PRSFX- Aromatherapy.wav'],
    'Aromatic Mist': ['music/battle_anims/PRSFX- Aromatic Mist.wav'],
    'Assist': ['music/battle_anims/PRSFX- Assist.wav'],
    'Assurance': ['music/battle_anims/PRSFX- Assurance.wav'],
    'Astonish': ['music/battle_anims/PRSFX- Astonish1.wav', 'music/battle_anims/PRSFX- Astonish2.wav'],
    'Attack Order': ['music/battle_anims/PRSFX- Attack Order1.wav', 'music/battle_anims/PRSFX- Attack Order2.wav'],
    'Attract': ['music/battle_anims/PRSFX- Attract.wav', 'music/battle_anims/PRSFX- Attract1.wav', 'music/battle_anims/PRSFX- Attract2.wav'],
    'Aura Sphere': ['music/battle_anims/PRSFX- Aura Sphere1.wav', 'music/battle_anims/PRSFX- Aura Sphere2.wav'],
    'Aurora Beam': ['music/battle_anims/PRSFX- Aurora Beam.wav'],
    'Aurora Veil': ['music/battle_anims/PRSFX- Aurora Veil1.wav', 'music/battle_anims/PRSFX- Aurora Veil2.wav', 'music/battle_anims/PRSFX- Aurora Veil3.wav', 'music/battle_anims/PRSFX- Aurora Veil4.wav'],
    'Autotomize': ['music/battle_anims/PRSFX- Autotomize.wav', 'music/battle_anims/PRSFX- Autotomize1.m4a', 'music/battle_anims/PRSFX- Autotomize2.wav'],
    'Avalanche': ['music/battle_anims/PRSFX- Avalanche.wav'],
    'Baby-Doll Eyes': ['music/battle_anims/PRSFX- Baby Doll Eyes.wav'],
    'Baneful Bunker': ['music/battle_anims/PRSFX- Baneful Bunker1.wav', 'music/battle_anims/PRSFX- Baneful Bunker2.wav', 'music/battle_anims/PRSFX- Baneful Bunker3.wav'],
    'Barrage': ['music/battle_anims/PRSFX- Barrage1.wav', 'music/battle_anims/PRSFX- Barrage2.wav'],
    'Barrier': ['music/battle_anims/PRSFX- Barrier.wav'],
    'Baton Pass': ['music/battle_anims/PRSFX- Baton Pass1.wav', 'music/battle_anims/PRSFX- Baton Pass2.wav'],
    'Beak Blast': ['music/battle_anims/PRSFX- Beak Blast1.wav', 'music/battle_anims/PRSFX- Beak Blast2.wav', 'music/battle_anims/PRSFX- Beak Blast3.wav', 'music/battle_anims/PRSFX- Beak Blast4.wav'],
    'Beat Up': ['music/battle_anims/PRSFX- Beat Up.wav'],
    'Belch': ['music/battle_anims/PRSFX- Belch1.wav', 'music/battle_anims/PRSFX- Belch2.wav', 'music/battle_anims/PRSFX- Belch3.wav'],
    'Belly Drum': ['music/battle_anims/PRSFX- Belly Drum.wav'],
    'Bestow': ['music/battle_anims/PRSFX- Bestow1.wav', 'music/battle_anims/PRSFX- Bestow2.wav'],
    'Bide': ['music/battle_anims/PRSFX- Bide1.wav', 'music/battle_anims/PRSFX- Bide2.wav'],
    'Bind': ['music/battle_anims/PRSFX- Bind.wav'],
    'Bite': ['music/battle_anims/PRSFX- Bite.wav'],
    'Black Hole Eclipse': ['music/battle_anims/PRSFX- Black Hole Eclipse1.wav', 'music/battle_anims/PRSFX- Black Hole Eclipse2.wav', 'music/battle_anims/PRSFX- Black Hole Eclipse3.wav', 'music/battle_anims/PRSFX- Black Hole Eclipse4.wav'],
    'Blast Burn': ['music/battle_anims/PRSFX- Blast Burn.wav', 'music/battle_anims/PRSFX- Blast Burn2.wav', 'music/battle_anims/PRSFX- Blast Burn3.wav'],
    'Blaze Kick': ['music/battle_anims/PRSFX- Blaze Kick1.wav', 'music/battle_anims/PRSFX- Blaze Kick2.wav'],
    'Blizzard': ['music/battle_anims/PRSFX- Blizzard.wav'],
    'Block': ['music/battle_anims/PRSFX- Block.wav'],
    'Bloom Doom': ['music/battle_anims/PRSFX- Bloom Doom1.wav', 'music/battle_anims/PRSFX- Bloom Doom2.wav', 'music/battle_anims/PRSFX- Bloom Doom3.wav'],
    'Blue Flare': ['music/battle_anims/PRSFX- Blue Flare1.wav', 'music/battle_anims/PRSFX- Blue Flare2.wav'],
    'Body Slam': ['music/battle_anims/PRSFX- Body Slam1.wav', 'music/battle_anims/PRSFX- Body Slam2.wav'],
    'Bolt Strike': ['music/battle_anims/PRSFX- Bolt Strike1.wav', 'music/battle_anims/PRSFX- Bolt Strike2.wav'],
    'Bone Club': ['music/battle_anims/PRSFX- Bone Club1.wav', 'music/battle_anims/PRSFX- Bone Club2.wav'],
    'Bone Rush': ['music/battle_anims/PRSFX- Bone Rush1.wav', 'music/battle_anims/PRSFX- Bone Rush2.wav'],
    'Bonemerang': ['music/battle_anims/PRSFX- Bonemerang1.wav', 'music/battle_anims/PRSFX- Bonemerang2.wav'],
    'Boomburst': ['music/battle_anims/PRSFX- Boomburst.wav'],
    'Bounce': ['music/battle_anims/PRSFX- Bounce1.wav', 'music/battle_anims/PRSFX- Bounce2.wav', 'music/battle_anims/PRSFX- Bounce3.wav', 'music/battle_anims/PRSFX- Bounce4.wav'],
    'Brave Bird': ['music/battle_anims/PRSFX- Brave Bird1.wav', 'music/battle_anims/PRSFX- Brave Bird2.wav'],
    'Brick Break': ['music/battle_anims/PRSFX- Brick Break1.wav', 'music/battle_anims/PRSFX- Brick Break2.wav'],
    'Brine': ['music/battle_anims/PRSFX- Brine.wav'],
    'Brutal Swing': ['music/battle_anims/PRSFX- Brutal Swing1.wav', 'music/battle_anims/PRSFX- Brutal Swing2.wav', 'music/battle_anims/PRSFX- Brutal Swing3.wav'],
    'Bubble': ['music/battle_anims/PRSFX- Bubble.wav'],
    'Bubble Beam': ['music/battle_anims/PRSFX- Bubblebeam.wav'],
    'Bug Bite': ['music/battle_anims/PRSFX- Bug Bite.wav'],
    'Bug Buzz': ['music/battle_anims/PRSFX- Bug Buzz.wav'],
    'Bulk Up': ['music/battle_anims/PRSFX- Bulk Up1.wav', 'music/battle_anims/PRSFX- Bulk Up2.wav'],
    'Bulldoze': ['music/battle_anims/PRSFX- Bulldoze.wav'],
    'Bullet Punch': ['music/battle_anims/PRSFX- Bullet Punch.wav'],
    'Bullet Seed': ['music/battle_anims/PRSFX- Bullet Seed.wav'],
    'Burn': ['music/battle_anims/PRSFX- Burn.wav'],
    'Burn Up': ['music/battle_anims/PRSFX- Burn Up1.wav', 'music/battle_anims/PRSFX- Burn Up2.wav'],
    'Calm Mind': ['music/battle_anims/PRSFX- Calm Mind.wav'],
    'Camouflage': ['music/battle_anims/PRSFX- Camouflage.wav'],
    'Captivate': ['music/battle_anims/PRSFX- Captivate.wav'],
    'Catastropika': ['music/battle_anims/PRSFX- Catastropika1.wav', 'music/battle_anims/PRSFX- Catastropika2.wav', 'music/battle_anims/PRSFX- Catastropika3.wav', 'music/battle_anims/PRSFX- Catastropika4.wav', 'music/battle_anims/PRSFX- Catastropika5.wav', 'music/battle_anims/PRSFX- Catastropika6.wav'],
    'Charge': ['music/battle_anims/PRSFX- Charge.wav'],
    'Charge Beam': ['music/battle_anims/PRSFX- Charge Beam.wav'],
    'Charm': ['music/battle_anims/PRSFX- Charm.wav'],
    'Chatter': ['music/battle_anims/PRSFX- Chatter.wav'],
    'Chip Away': ['music/battle_anims/PRSFX- Chip Away.wav'],
    'Circle Throw': ['music/battle_anims/PRSFX- Circle Throw1.wav', 'music/battle_anims/PRSFX- Circle Throw2.wav'],
    'Clamp': ['music/battle_anims/PRSFX- Clamp1.wav', 'music/battle_anims/PRSFX- Clamp2.wav', 'music/battle_anims/PRSFX- Clamp3.wav'],
    'Clear Smog': ['music/battle_anims/PRSFX- Clear Smog.wav'],
    'Close Combat': ['music/battle_anims/PRSFX- Close Combat.wav'],
    'Coil': ['music/battle_anims/PRSFX- Coil.wav'],
    'Comet Punch': ['music/battle_anims/PRSFX- Comet Punch.wav'],
    'Confide': ['music/battle_anims/PRSFX- Confide.wav'],
    'Confuse Ray': ['music/battle_anims/PRSFX- Confuse Ray.wav'],
    'Confused': ['music/battle_anims/PRSFX- Confused.wav'],
    'Confusion': ['music/battle_anims/PRSFX- Confusion.wav'],
    'Constrict': ['music/battle_anims/PRSFX- Constrict.wav'],
    'Conversion': ['music/battle_anims/PRSFX- Conversion.wav', 'music/battle_anims/PRSFX- Conversion2.wav'],
    'Cosmic Power': ['music/battle_anims/PRSFX- Cosmic Power.wav'],
    'Cotton Guard': ['music/battle_anims/PRSFX- Cotton Guard.wav'],
    'Cotton Spore': ['music/battle_anims/PRSFX- Cotton Spore.wav'],
    'Counter': ['music/battle_anims/PRSFX- Counter1.wav', 'music/battle_anims/PRSFX- Counter2.wav'],
    'Covet': ['music/battle_anims/PRSFX- Covet1.wav', 'music/battle_anims/PRSFX- Covet2.wav'],
    'Crabhammer': ['music/battle_anims/PRSFX- Crabhammer.wav'],
    'Crafty Shield': ['music/battle_anims/PRSFX- Crafty Shield.wav'],
    'Cross Chop': ['music/battle_anims/PRSFX- Cross Chop1.wav', 'music/battle_anims/PRSFX- Cross Chop2.wav'],
    'Cross Poison': ['music/battle_anims/PRSFX- Cross Poison1.wav', 'music/battle_anims/PRSFX- Cross Poison2.wav'],
    'Crunch': ['music/battle_anims/PRSFX- Crunch.wav'],
    'Crush Claw': ['music/battle_anims/PRSFX- Crush Claw.wav'],
    'Crush Grip': ['music/battle_anims/PRSFX- Crush Grip1.wav', 'music/battle_anims/PRSFX- Crush Grip2.wav'],
    'Curse': ['music/battle_anims/PRSFX- Curse.wav', 'music/battle_anims/PRSFX- Curse2.wav'],
    'Cut': ['music/battle_anims/PRSFX- Cut.wav'],
    'Dark Pulse': ['music/battle_anims/PRSFX- Dark Pulse1.wav', 'music/battle_anims/PRSFX- Dark Pulse2.wav'],
    'Dark Void': ['music/battle_anims/PRSFX- Dark Void.wav'],
    'Dazzling Gleam': ['music/battle_anims/PRSFX- Dazzling Gleam.wav'],
    'Defend Order': ['music/battle_anims/PRSFX- Defend Order1.wav', 'music/battle_anims/PRSFX- Defend Order2.wav'],
    'Defense Curl': ['music/battle_anims/PRSFX- Defense Curl1.wav', 'music/battle_anims/PRSFX- Defense Curl2.wav'],
    'Defog': ['music/battle_anims/PRSFX- Defog.wav'],
    'Destiny Bond': ['music/battle_anims/PRSFX- Destiny Bond1.wav', 'music/battle_anims/PRSFX- Destiny Bond2.wav'],
    'Detect': ['music/battle_anims/PRSFX- Detect.wav'],
    'Devastating Drake': ['music/battle_anims/PRSFX- Devastating Drake1.wav', 'music/battle_anims/PRSFX- Devastating Drake2.wav', 'music/battle_anims/PRSFX- Devastating Drake3.wav'],
    'Diamond Storm': ['music/battle_anims/PRSFX- Diamond Storm1.wav', 'music/battle_anims/PRSFX- Diamond Storm2.wav'],
    'Dig': ['music/battle_anims/PRSFX- Dig1.wav', 'music/battle_anims/PRSFX- Dig2.wav'],
    'Disable': ['music/battle_anims/PRSFX- Disable.wav'],
    'Discharge': ['music/battle_anims/PRSFX- Discharge.wav'],
    'Dive': ['music/battle_anims/PRSFX- Dive1.wav', 'music/battle_anims/PRSFX- Dive2.wav', 'music/battle_anims/PRSFX- Dive3.wav'],
    'Dizzy Punch': ['music/battle_anims/PRSFX- Dizzy Punch1.wav', 'music/battle_anims/PRSFX- Dizzy Punch2.wav'],
    'Doom Desire': ['music/battle_anims/PRSFX- Doom Desire1.wav', 'music/battle_anims/PRSFX- Doom Desire2.wav'],
    'Double-Edge': ['music/battle_anims/PRSFX- Double Edge1.wav', 'music/battle_anims/PRSFX- Double Edge2.wav'],
    'Double Hit': ['music/battle_anims/PRSFX- Double Hit.wav'],
    'Double Kick': ['music/battle_anims/PRSFX- Double Kick.wav'],
    'Double Slap': ['music/battle_anims/PRSFX- Double Slap.wav'],
    'Double Team': ['music/battle_anims/PRSFX- Double Team.wav'],
    'Draco Meteor': ['music/battle_anims/PRSFX- Draco Meteor1.wav', 'music/battle_anims/PRSFX- Draco Meteor2.wav', 'music/battle_anims/PRSFX- Draco Meteor3.wav'],
    'Dragon Ascent': ['music/battle_anims/PRSFX- Dragon Ascent1.wav', 'music/battle_anims/PRSFX- Dragon Ascent2.wav', 'music/battle_anims/PRSFX- Dragon Ascent3.wav'],
    'Dragon Breath': ['music/battle_anims/PRSFX- Dragon Breath.wav'],
    'Dragon Claw': ['music/battle_anims/PRSFX- Dragon Claw.wav'],
    'Dragon Dance': ['music/battle_anims/PRSFX- Dragon Dance.wav'],
    'Dragon Pulse': ['music/battle_anims/PRSFX- Dragon Pulse.wav'],
    'Dragon Rage': ['music/battle_anims/PRSFX- Dragon Rage.wav'],
    'Dragon Rush': ['music/battle_anims/PRSFX- Dragon Rush1.wav', 'music/battle_anims/PRSFX- Dragon Rush2.wav'],
    'Dragon Tail': ['music/battle_anims/PRSFX- Dragon Tail.wav'],
    'Drain Punch': ['music/battle_anims/PRSFX- Drain Punch1.wav', 'music/battle_anims/PRSFX- Drain Punch2.wav'],
    'Draining Kiss': ['music/battle_anims/PRSFX- Draining Kiss1.wav', 'music/battle_anims/PRSFX- Draining Kiss2.wav'],
    'Dream Eater': ['music/battle_anims/PRSFX- Dream Eater1.wav', 'music/battle_anims/PRSFX- Dream Eater2.wav', 'music/battle_anims/PRSFX- Dream Eater3.wav'],
    'Drill Peck': ['music/battle_anims/PRSFX- Drill Peck.wav'],
    'Drill Run': ['music/battle_anims/PRSFX- Drill Run.wav'],
    'Dual Chop': ['music/battle_anims/PRSFX- Dual Chop.wav'],
    'Dynamic Punch': ['music/battle_anims/PRSFX- Dynamic Punch1.wav', 'music/battle_anims/PRSFX- Dynamic Punch2.wav'],
    'Earth Power': ['music/battle_anims/PRSFX- Earth Power.wav'],
    'Earthquake': ['music/battle_anims/PRSFX- Earthquake.wav', 'music/battle_anims/PRSFX- Earthquake1.wav', 'music/battle_anims/PRSFX- Earthquake2.wav'],
    'Echoed Voice': ['music/battle_anims/PRSFX- Echoed Voice.wav'],
    'Eerie Impulse': ['music/battle_anims/PRSFX- Eerie Impulse.wav'],
    'Egg Bomb': ['music/battle_anims/PRSFX- Egg Bomb1.wav', 'music/battle_anims/PRSFX- Egg Bomb2.wav'],
    'Electric Terrain': ['music/battle_anims/PRSFX- Electric Terrain.wav', 'music/battle_anims/PRSFX- Electric Terrain2.wav'],
    'Electrify': ['music/battle_anims/PRSFX- Electrify.wav'],
    'Electro Ball': ['music/battle_anims/PRSFX- Electro Ball1.wav', 'music/battle_anims/PRSFX- Electro Ball2.wav'],
    'Electroweb': ['music/battle_anims/PRSFX- Electroweb1.wav', 'music/battle_anims/PRSFX- Electroweb2.wav'],
    'Embargo': ['music/battle_anims/PRSFX- Embargo.wav'],
    'Ember': ['music/battle_anims/PRSFX- Ember.wav'],
    'Encore': ['music/battle_anims/PRSFX- Encore.wav'],
    'Endeavor': ['music/battle_anims/PRSFX- Endeavor1.wav', 'music/battle_anims/PRSFX- Endeavor2.wav'],
    'Endure': ['music/battle_anims/PRSFX- Endure.wav'],
    'Energy Ball': ['music/battle_anims/PRSFX- Energy Ball1.wav', 'music/battle_anims/PRSFX- Energy Ball2.wav'],
    'Entrainment': ['music/battle_anims/PRSFX- Entrainment.wav'],
    'Eruption': ['music/battle_anims/PRSFX- Eruption1.wav', 'music/battle_anims/PRSFX- Eruption2.wav'],
    'Explosion': ['music/battle_anims/PRSFX- Explosion.wav', 'music/battle_anims/PRSFX- Explosion2.wav'],
    'Extrasensory': ['music/battle_anims/PRSFX- Extrasensory.wav'],
    'Extreme Evoboost': ['music/battle_anims/PRSFX- Extreme Evoboost1.wav', 'music/battle_anims/PRSFX- Extreme Evoboost2.wav', 'music/battle_anims/PRSFX- Extreme Evoboost3.wav'],
    'Extreme Speed': ['music/battle_anims/PRSFX- Extremespeed1.wav', 'music/battle_anims/PRSFX- Extremespeed2.wav'],
    'Facade': ['music/battle_anims/PRSFX- Facade1.wav', 'music/battle_anims/PRSFX- Facade2.wav'],
    'Fairy Lock': ['music/battle_anims/PRSFX- Fairy Lock.wav'],
    'Fairy Wind': ['music/battle_anims/PRSFX- Fairy Wind.wav'],
    'Fake Out': ['music/battle_anims/PRSFX- Fake Out1.wav', 'music/battle_anims/PRSFX- Fake Out2.wav'],
    'Fake Tears': ['music/battle_anims/PRSFX- Fake Tears.wav'],
    'False Swipe': ['music/battle_anims/PRSFX- False Swipe.wav'],
    'Feather Dance': ['music/battle_anims/PRSFX- Featherdance1.wav', 'music/battle_anims/PRSFX- Featherdance2.wav'],
    'Feint': ['music/battle_anims/PRSFX- Feint1.wav', 'music/battle_anims/PRSFX- Feint2.wav'],
    'Feint Attack': ['music/battle_anims/PRSFX- Feint Attack1.wav', 'music/battle_anims/PRSFX- Feint Attack2.wav'],
    'Fell Stinger': ['music/battle_anims/PRSFX- Fell Stinger1.wav', 'music/battle_anims/PRSFX- Fell Stinger2.wav', 'music/battle_anims/PRSFX- Fell Stinger3.wav'],
    'Fiery Dance': ['music/battle_anims/PRSFX- Fiery Dance1.wav', 'music/battle_anims/PRSFX- Fiery Dance2.wav'],
    'Final Gambit': ['music/battle_anims/PRSFX- Final Gambit1.wav', 'music/battle_anims/PRSFX- Final Gambit2.wav'],
    'Fire Blast': ['music/battle_anims/PRSFX- Fire Blast.wav'],
    'Fire Fang': ['music/battle_anims/PRSFX- Fire Fang1.wav', 'music/battle_anims/PRSFX- Fire Fang2.wav'],
    'Fire Lash': ['music/battle_anims/PRSFX- Fire Lash1.wav', 'music/battle_anims/PRSFX- Fire Lash2.wav', 'music/battle_anims/PRSFX- Fire Lash3.wav', 'music/battle_anims/PRSFX- Fire Lash4.wav'],
    'Fire Pledge': ['music/battle_anims/PRSFX- Fire Pledge.wav'],
    'Fire Punch': ['music/battle_anims/PRSFX- Fire Punch1.wav', 'music/battle_anims/PRSFX- Fire Punch2.wav', 'music/battle_anims/PRSFX- Fire Punch3.wav'],
    'Fire Spin': ['music/battle_anims/PRSFX- Fire Spin.wav'],
    'Fissure': ['music/battle_anims/PRSFX- Fissure.wav'],
    'Flail': ['music/battle_anims/PRSFX- Flail.wav'],
    'Flame Burst': ['music/battle_anims/PRSFX- Flame Burst.wav'],
    'Flame Charge': ['music/battle_anims/PRSFX- Flame Charge1.wav', 'music/battle_anims/PRSFX- Flame Charge2.wav'],
    'Flame Wheel': ['music/battle_anims/PRSFX- Flame Wheel1.wav', 'music/battle_anims/PRSFX- Flame Wheel2.wav'],
    'Flamethrower': ['music/battle_anims/PRSFX- Flamethrower.wav'],
    'Flare Blitz': ['music/battle_anims/PRSFX- Flare Blitz1.wav', 'music/battle_anims/PRSFX- Flare Blitz2.wav', 'music/battle_anims/PRSFX- Flare Blitz3.wav'],
    'Flash': ['music/battle_anims/PRSFX- Flash.wav'],
    'Flash Cannon': ['music/battle_anims/PRSFX- Flash Cannon.wav'],
    'Flatter': ['music/battle_anims/PRSFX- Flatter.wav'],
    'Fling': ['music/battle_anims/PRSFX- Fling1.wav', 'music/battle_anims/PRSFX- Fling2.wav'],
    'Floral Healing': ['music/battle_anims/PRSFX- Floral Healing1.wav', 'music/battle_anims/PRSFX- Floral Healing2.wav'],
    'Flower Shield': ['music/battle_anims/PRSFX- Flower Shield.wav'],
    'Fly': ['music/battle_anims/PRSFX- Fly1.wav', 'music/battle_anims/PRSFX- Fly2.wav'],
    'Flying Press': ['music/battle_anims/PRSFX- Flying Press1.wav', 'music/battle_anims/PRSFX- Flying Press2.wav', 'music/battle_anims/PRSFX- Flying Press3.wav'],
    'Focus Blast': ['music/battle_anims/PRSFX- Focus Blast1.wav', 'music/battle_anims/PRSFX- Focus Blast2.wav', 'music/battle_anims/PRSFX- Focus Blast3.wav'],
    'Focus Energy': ['music/battle_anims/PRSFX- Focus Energy.wav'],
    'Focus Punch': ['music/battle_anims/PRSFX- Focus Punch1.wav', 'music/battle_anims/PRSFX- Focus Punch2.wav', 'music/battle_anims/PRSFX- Focus Punch3.wav'],
    'Follow Me': ['music/battle_anims/PRSFX- Follow Me.wav'],
    'Force Palm': ['music/battle_anims/PRSFX- Force Palm1.wav', 'music/battle_anims/PRSFX- Force Palm2.wav'],
    'Foresight': ['music/battle_anims/PRSFX- Foresight1.wav', 'music/battle_anims/PRSFX- Foresight2.wav'],
    'Forest\'s Curse': ['music/battle_anims/PRSFX- Forests Curse.wav'],
    'Foul Play': ['music/battle_anims/PRSFX- Foul Play1.wav', 'music/battle_anims/PRSFX- Foul Play2.wav'],
    'Freeze-Dry': ['music/battle_anims/PRSFX- Freeze Dry1.wav', 'music/battle_anims/PRSFX- Freeze Dry2.wav', 'music/battle_anims/PRSFX- Freeze Dry3.wav'],
    'Freeze Shock': ['music/battle_anims/PRSFX- Freeze Shock1.wav', 'music/battle_anims/PRSFX- Freeze Shock2.wav', 'music/battle_anims/PRSFX- Freeze Shock3.wav'],
    'Frenzy Plant': ['music/battle_anims/PRSFX- Frenzy Plant1.wav', 'music/battle_anims/PRSFX- Frenzy Plant2.wav'],
    'Frost Breath': ['music/battle_anims/PRSFX- Frost Breath1.wav', 'music/battle_anims/PRSFX- Frost Breath2.wav'],
    'Frozen': ['music/battle_anims/PRSFX- Frozen.wav'],
    'Frustration': ['music/battle_anims/PRSFX- Frustration1.wav', 'music/battle_anims/PRSFX- Frustration2.wav'],
    'Fury Attack': ['music/battle_anims/PRSFX- Fury Attack.wav'],
    'Fury Cutter': ['music/battle_anims/PRSFX- Fury Cutter.wav'],
    'Fury Swipes': ['music/battle_anims/PRSFX- Fury Swipes.wav'],
    'Fusion Bolt': ['music/battle_anims/PRSFX- Fusion Bolt1.wav', 'music/battle_anims/PRSFX- Fusion Bolt2.wav'],
    'Fusion Flare': ['music/battle_anims/PRSFX- Fusion Flare1.wav', 'music/battle_anims/PRSFX- Fusion Flare2.wav', 'music/battle_anims/PRSFX- Fusion Flare3.wav'],
    'FusionFlare': ['music/battle_anims/PRSFX- FusionFlare3.wav'],
    'Future Sight': ['music/battle_anims/PRSFX- Future Sight1.wav', 'music/battle_anims/PRSFX- Future Sight2.wav'],
    'Gastro Acid': ['music/battle_anims/PRSFX- Gastro Acid.wav'],
    'Gear Grind': ['music/battle_anims/PRSFX- Gear Grind.wav'],
    'Gear Up': ['music/battle_anims/PRSFX- Gear Up1.wav', 'music/battle_anims/PRSFX- Gear Up2.wav', 'music/battle_anims/PRSFX- Gear Up3.wav', 'music/battle_anims/PRSFX- Gear Up4.wav', 'music/battle_anims/PRSFX- Gear Up5.wav', 'music/battle_anims/PRSFX- Gear Up6.wav'],
    'Geomancy': ['music/battle_anims/PRSFX- Geomancy.wav'],
    'Giga Drain': ['music/battle_anims/PRSFX- Giga Drain1.wav', 'music/battle_anims/PRSFX- Giga Drain2.wav'],
    'Giga Impact': ['music/battle_anims/PRSFX- Giga Impact1.wav', 'music/battle_anims/PRSFX- Giga Impact2.wav'],
    'Gigavolt Havoc': ['music/battle_anims/PRSFX- Gigavolt Havoc1.wav', 'music/battle_anims/PRSFX- Gigavolt Havoc2.wav', 'music/battle_anims/PRSFX- Gigavolt Havoc3.wav'],
    'Glaciate': ['music/battle_anims/PRSFX- Glaciate1.wav', 'music/battle_anims/PRSFX- Glaciate2.wav'],
    'Glare': ['music/battle_anims/PRSFX- Glare.wav'],
    'Glitch': ['music/battle_anims/PRSFX- Glitch1.wav', 'music/battle_anims/PRSFX- Glitch2.wav'],
    'Grass Knot': ['music/battle_anims/PRSFX- Grass Knot1.wav', 'music/battle_anims/PRSFX- Grass Knot2.wav'],
    'Grass Pledge': ['music/battle_anims/PRSFX- Grass Pledge1.wav', 'music/battle_anims/PRSFX- Grass Pledge2.wav'],
    'Grass Whistle': ['music/battle_anims/PRSFX- Grass Whistle.wav'],
    'Grassy Terrain': ['music/battle_anims/PRSFX- Grassy Terrain.wav'],
    'Gravity': ['music/battle_anims/PRSFX- Gravity.wav'],
    'Growth': ['music/battle_anims/PRSFX- Growth.wav'],
    'Grudge': ['music/battle_anims/PRSFX- Grudge.wav'],
    'Guard Split': ['music/battle_anims/PRSFX- Guard Split.wav'],
    'Guard Swap': ['music/battle_anims/PRSFX- Guard Swap.wav'],
    'Guillotine': ['music/battle_anims/PRSFX- Guillotine1.wav', 'music/battle_anims/PRSFX- Guillotine2.wav'],
    'Gunk Shot': ['music/battle_anims/PRSFX- Gunk Shot.wav'],
    'Gust': ['music/battle_anims/PRSFX- Gust.wav'],
    'Gyro Ball': ['music/battle_anims/PRSFX- Gyro Ball1.wav', 'music/battle_anims/PRSFX- Gyro Ball2.wav'],
    'Hail': ['music/battle_anims/PRSFX- Hail.wav'],
    'HailMove': ['music/battle_anims/PRSFX- HailMove.wav'],
    'Hammer Arm': ['music/battle_anims/PRSFX- Hammer Arm1.wav', 'music/battle_anims/PRSFX- Hammer Arm2.wav'],
    'Harden': ['music/battle_anims/PRSFX- Harden.wav'],
    'Haze': ['music/battle_anims/PRSFX- Haze.wav'],
    'Head Charge': ['music/battle_anims/PRSFX- Head Charge.wav'],
    'Head Smash': ['music/battle_anims/PRSFX- Head Smash.wav'],
    'Headbutt': ['music/battle_anims/PRSFX- Headbutt1.wav', 'music/battle_anims/PRSFX- Headbutt2.wav'],
    'Heal Bell': ['music/battle_anims/PRSFX- Heal Bell.wav'],
    'Heal Block': ['music/battle_anims/PRSFX- Heal Block.wav'],
    'Heal Order': ['music/battle_anims/PRSFX- Heal Order1.wav', 'music/battle_anims/PRSFX- Heal Order2.wav'],
    'Healing Pulse': ['music/battle_anims/PRSFX- Healing Pulse.wav'],
    'Healing Wish': ['music/battle_anims/PRSFX- Healing Wish.wav'],
    'Health Down': ['music/battle_anims/PRSFX- Health Down.wav'],
    'Health Up': ['music/battle_anims/PRSFX- Health Up.wav'],
    'Heart Stamp': ['music/battle_anims/PRSFX- Heart Stamp1.wav', 'music/battle_anims/PRSFX- Heart Stamp2.wav'],
    'Heart Swap': ['music/battle_anims/PRSFX- Heart Swap.wav'],
    'Heat Crash': ['music/battle_anims/PRSFX- Heat Crash.wav'],
    'Heat Wave': ['music/battle_anims/PRSFX- Heat Wave.wav'],
    'Heavy Slam': ['music/battle_anims/PRSFX- Heavy Slam1.wav', 'music/battle_anims/PRSFX- Heavy Slam2.wav'],
    'Helping Hand': ['music/battle_anims/PRSFX- Helping Hand.wav'],
    'Hex': ['music/battle_anims/PRSFX- Hex.wav'],
    'High Jump Kick': ['music/battle_anims/PRSFX- Hi Jump Kick1.wav', 'music/battle_anims/PRSFX- Hi Jump Kick2.wav'],
    'Hidden Power': ['music/battle_anims/PRSFX- Hidden Power1.wav', 'music/battle_anims/PRSFX- Hidden Power2.wav'],
    'High Horsepower': ['music/battle_anims/PRSFX- High Horse Power1.wav', 'music/battle_anims/PRSFX- High Horse Power2.wav'],
    'Hone Claws': ['music/battle_anims/PRSFX- Hone Claws.wav'],
    'Horn Attack': ['music/battle_anims/PRSFX- Horn Attack.wav'],
    'Horn Drill': ['music/battle_anims/PRSFX- Horn Drill1.wav', 'music/battle_anims/PRSFX- Horn Drill2.wav', 'music/battle_anims/PRSFX- Horn Drill3.wav'],
    'Horn Drill3_': ['music/battle_anims/PRSFX- Horn Drill3_1.m4a'],
    'Horn Leech': ['music/battle_anims/PRSFX- Horn Leech1.wav', 'music/battle_anims/PRSFX- Horn Leech2.wav'],
    'Hurricane': ['music/battle_anims/PRSFX- Hurricane.wav'],
    'Hydro Cannon': ['music/battle_anims/PRSFX- Hydro Cannon.wav', 'music/battle_anims/PRSFX- Hydro Cannon1.wav', 'music/battle_anims/PRSFX- Hydro Cannon2.wav'],
    'Hydro Pump': ['music/battle_anims/PRSFX- Hydro Pump.wav'],
    'Hydro Vortex': ['music/battle_anims/PRSFX- Hydro Vortex1.wav', 'music/battle_anims/PRSFX- Hydro Vortex2.wav', 'music/battle_anims/PRSFX- Hydro Vortex3.wav'],
    'Hyper Beam': ['music/battle_anims/PRSFX- Hyper Beam.wav'],
    'Hyper Fang': ['music/battle_anims/PRSFX- Hyper Fang.wav'],
    'Hyperspace Fury': ['music/battle_anims/PRSFX- Hyperspace Fury1.wav', 'music/battle_anims/PRSFX- Hyperspace Fury2.wav'],
    'Hyperspace Hole': ['music/battle_anims/PRSFX- Hyperspace Hole1.wav', 'music/battle_anims/PRSFX- Hyperspace Hole2.wav'],
    'Hypnosis': ['music/battle_anims/PRSFX- Hypnosis.wav'],
    'Ice Ball': ['music/battle_anims/PRSFX- Ice Ball1.wav', 'music/battle_anims/PRSFX- Ice Ball2.wav'],
    'Ice Beam': ['music/battle_anims/PRSFX- Ice Beam.wav'],
    'Ice Burn': ['music/battle_anims/PRSFX- Ice Burn1.wav', 'music/battle_anims/PRSFX- Ice Burn2.wav', 'music/battle_anims/PRSFX- Ice Burn3.wav', 'music/battle_anims/PRSFX- Ice Burn4.wav'],
    'Ice Fang': ['music/battle_anims/PRSFX- Ice Fang1.wav', 'music/battle_anims/PRSFX- Ice Fang2.wav'],
    'Ice Hammer': ['music/battle_anims/PRSFX- Ice Hammer1.wav', 'music/battle_anims/PRSFX- Ice Hammer2.wav'],
    'Ice Punch': ['music/battle_anims/PRSFX- Ice Punch1.wav', 'music/battle_anims/PRSFX- Ice Punch2.wav'],
    'Ice Shard': ['music/battle_anims/PRSFX- Ice Shard.wav'],
    'Icicle Crash': ['music/battle_anims/PRSFX- Icicle Crash1.wav', 'music/battle_anims/PRSFX- Icicle Crash2.wav'],
    'Icicle Spear': ['music/battle_anims/PRSFX- Icicle Spear.wav'],
    'Icy Wind': ['music/battle_anims/PRSFX- Icy Wind1.wav', 'music/battle_anims/PRSFX- Icy Wind2.wav'],
    'Imprison': ['music/battle_anims/PRSFX- Imprison1.wav', 'music/battle_anims/PRSFX- Imprison2.wav'],
    'Incinerate': ['music/battle_anims/PRSFX- Incinerate1.wav', 'music/battle_anims/PRSFX- Incinerate2.wav'],
    'Inferno': ['music/battle_anims/PRSFX- Inferno.wav'],
    'Inferno Overdrive': ['music/battle_anims/PRSFX- Inferno Overdrive1.wav', 'music/battle_anims/PRSFX- Inferno Overdrive2.wav', 'music/battle_anims/PRSFX- Inferno Overdrive3.wav', 'music/battle_anims/PRSFX- Inferno Overdrive4.wav', 'music/battle_anims/PRSFX- Inferno Overdrive5.wav'],
    'Infestation': ['music/battle_anims/PRSFX- Infestation.wav'],
    'Ingrain': ['music/battle_anims/PRSFX- Ingrain1.wav', 'music/battle_anims/PRSFX- Ingrain2.wav'],
    'Instruct': ['music/battle_anims/PRSFX- Instruct1.wav', 'music/battle_anims/PRSFX- Instruct2.wav'],
    'Ion Deluge': ['music/battle_anims/PRSFX- Ion Deluge.wav'],
    'Iron Defense': ['music/battle_anims/PRSFX- Iron Defense.wav'],
    'Iron Head': ['music/battle_anims/PRSFX- Iron Head.wav'],
    'Iron Tail': ['music/battle_anims/PRSFX- Iron Tail1.wav', 'music/battle_anims/PRSFX- Iron Tail2.wav'],
    'Judgment': ['music/battle_anims/PRSFX- Judgment.wav'],
    'Jump Kick': ['music/battle_anims/PRSFX- Jump Kick1.wav', 'music/battle_anims/PRSFX- Jump Kick2.wav'],
    'Karate Chop': ['music/battle_anims/PRSFX- Karate Chop1.wav', 'music/battle_anims/PRSFX- Karate Chop2.wav'],
    'Kinesis': ['music/battle_anims/PRSFX- Kinesis.wav'],
    'King\'s Shield': ['music/battle_anims/PRSFX- King\'s Shield1.wav', 'music/battle_anims/PRSFX- King\'s Shield2.wav'],
    'Knock Off': ['music/battle_anims/PRSFX- Knock Off.wav'],
    'Land\'s Wrath': ['music/battle_anims/PRSFX- Lands Wrath1.wav', 'music/battle_anims/PRSFX- Lands Wrath2.wav'],
    'Laser Focus': ['music/battle_anims/PRSFX- Laser Focus1.wav', 'music/battle_anims/PRSFX- Laser Focus2.wav'],
    'Last Resort': ['music/battle_anims/PRSFX- Last Resort1.wav', 'music/battle_anims/PRSFX- Last Resort2.wav'],
    'Lava Plume': ['music/battle_anims/PRSFX- Lava Plume.wav'],
    'Leaf Blade': ['music/battle_anims/PRSFX- Leaf Blade.wav'],
    'Leaf Storm': ['music/battle_anims/PRSFX- Leaf Storm1.wav', 'music/battle_anims/PRSFX- Leaf Storm2.wav'],
    'Leaf Tornado': ['music/battle_anims/PRSFX- Leaf Tornado1.wav', 'music/battle_anims/PRSFX- Leaf Tornado2.wav'],
    'Leafage': ['music/battle_anims/PRSFX- Leafage 1.wav', 'music/battle_anims/PRSFX- Leafage 2.wav'],
    'Leech Life': ['music/battle_anims/PRSFX- Leech Life1.wav', 'music/battle_anims/PRSFX- Leech Life2.wav'],
    'Leech Seed': ['music/battle_anims/PRSFX- Leech Seed1.wav', 'music/battle_anims/PRSFX- Leech Seed2.wav', 'music/battle_anims/PRSFX- Leech Seed3.wav'],
    'Leer': ['music/battle_anims/PRSFX- Leer.wav'],
    'Lick': ['music/battle_anims/PRSFX- Lick.wav'],
    'Light Screen': ['music/battle_anims/PRSFX- Light Screen.wav'],
    'Liquidation': ['music/battle_anims/PRSFX- Liquidation1.wav', 'music/battle_anims/PRSFX- Liquidation2.wav', 'music/battle_anims/PRSFX- Liquidation3.wav', 'music/battle_anims/PRSFX- Liquidation4.wav'],
    'Lock-On': ['music/battle_anims/PRSFX- Lock On.wav'],
    'Lovely Kiss': ['music/battle_anims/PRSFX- Lovely Kiss.wav'],
    'Low Kick': ['music/battle_anims/PRSFX- Low Kick.wav'],
    'Low Sweep': ['music/battle_anims/PRSFX- Low Sweep.wav'],
    'LTBTS': ['music/battle_anims/PRSFX- LTBTS1.wav', 'music/battle_anims/PRSFX- LTBTS2.wav', 'music/battle_anims/PRSFX- LTBTS3.wav', 'music/battle_anims/PRSFX- LTBTS4.wav'],
    'Lucky Chant': ['music/battle_anims/PRSFX- Lucky Chant.wav'],
    'Lunar Dance': ['music/battle_anims/PRSFX- Lunar Dance.wav'],
    'Luster Purge': ['music/battle_anims/PRSFX- Luster Purge1.wav', 'music/battle_anims/PRSFX- Luster Purge2.wav', 'music/battle_anims/PRSFX- Luster Purge3.wav'],
    'Mach Punch': ['music/battle_anims/PRSFX- Mach Punch.wav'],
    'Magic Coat': ['music/battle_anims/PRSFX- Magic Coat.wav'],
    'Magic Room': ['music/battle_anims/PRSFX- Magic Room.wav'],
    'Magical Leaf': ['music/battle_anims/PRSFX- Magical Leaf1.wav', 'music/battle_anims/PRSFX- Magical Leaf2.wav'],
    'Magma Storm': ['music/battle_anims/PRSFX- Magma Storm1.wav', 'music/battle_anims/PRSFX- Magma Storm2.wav'],
    'Magnet Bomb': ['music/battle_anims/PRSFX- Magnet Bomb1.wav', 'music/battle_anims/PRSFX- Magnet Bomb2.wav'],
    'Magnet Rise': ['music/battle_anims/PRSFX- Magnet Rise.wav'],
    'Magnetic Flux': ['music/battle_anims/PRSFX- Magnetic Flux.wav'],
    'Magnitude': ['music/battle_anims/PRSFX- Magnitude.wav'],
    'Mat Block': ['music/battle_anims/PRSFX- Mat Block.wav'],
    'Me First': ['music/battle_anims/PRSFX- Me First1.wav', 'music/battle_anims/PRSFX- Me First2.wav', 'music/battle_anims/PRSFX- Me First3.wav'],
    'Mean Look': ['music/battle_anims/PRSFX- Mean Look.wav'],
    'Meditate': ['music/battle_anims/PRSFX- Meditate.wav'],
    'Mega Drain': ['music/battle_anims/PRSFX- Mega Drain1.wav', 'music/battle_anims/PRSFX- Mega Drain2.wav'],
    'Mega Evolution': ['music/battle_anims/PRSFX- Mega Evolution1.wav', 'music/battle_anims/PRSFX- Mega Evolution2.wav'],
    'Mega Punch': ['music/battle_anims/PRSFX- Mega Punch1.wav', 'music/battle_anims/PRSFX- Mega Punch2.wav'],
    'Megahorn': ['music/battle_anims/PRSFX- Megahorn1.wav', 'music/battle_anims/PRSFX- Megahorn2.wav'],
    'Mega Kick': ['music/battle_anims/PRSFX- Megakick.wav'],
    'Memento': ['music/battle_anims/PRSFX- Memento1.wav', 'music/battle_anims/PRSFX- Memento2.wav'],
    'Metal Burst': ['music/battle_anims/PRSFX- Metal Burst1.wav', 'music/battle_anims/PRSFX- Metal Burst2.wav'],
    'Metal Claw': ['music/battle_anims/PRSFX- Metal Claw1.wav', 'music/battle_anims/PRSFX- Metal Claw2.wav'],
    'Metal Sound': ['music/battle_anims/PRSFX- Metal Sound.wav'],
    'Meteor Mash': ['music/battle_anims/PRSFX- Meteor Mash1.wav', 'music/battle_anims/PRSFX- Meteor Mash2.wav'],
    'Metronome': ['music/battle_anims/PRSFX- Metronome.wav'],
    'Milk Drink': ['music/battle_anims/PRSFX- Milk Drink.wav'],
    'Mimic': ['music/battle_anims/PRSFX- Mimic1.wav', 'music/battle_anims/PRSFX- Mimic2.wav'],
    'Mind Blown': ['music/battle_anims/PRSFX- Mind Blow1.wav', 'music/battle_anims/PRSFX- Mind Blow2.wav', 'music/battle_anims/PRSFX- Mind Blow3.wav', 'music/battle_anims/PRSFX- Mind Blow4.wav'],
    'Mind Reader': ['music/battle_anims/PRSFX- Mind Reader.wav'],
    'Minimize': ['music/battle_anims/PRSFX- Minimize1.wav', 'music/battle_anims/PRSFX- Minimize2.wav', 'music/battle_anims/PRSFX- Minimize3.wav'],
    'Miracle Eye': ['music/battle_anims/PRSFX- Miracle Eye.wav'],
    'Mirror Coat': ['music/battle_anims/PRSFX- Mirror Coat.wav'],
    'Mirror Shatter': ['music/battle_anims/PRSFX- Mirror Shatter.wav'],
    'Mirror Shot': ['music/battle_anims/PRSFX- Mirror Shot.wav'],
    'Mist': ['music/battle_anims/PRSFX- Mist.wav'],
    'Mist Ball': ['music/battle_anims/PRSFX- Mist Ball1.wav', 'music/battle_anims/PRSFX- Mist Ball2.wav'],
    'Misty Terrain': ['music/battle_anims/PRSFX- Misty Terrain.wav'],
    'Moonblast': ['music/battle_anims/PRSFX- Moonblast1.wav', 'music/battle_anims/PRSFX- Moonblast2.wav'],
    'Moonlight': ['music/battle_anims/PRSFX- Moonlight.wav'],
    'Morning Sun': ['music/battle_anims/PRSFX- Morning Sun.wav'],
    'Mud Bomb': ['music/battle_anims/PRSFX- Mud Bomb1.wav', 'music/battle_anims/PRSFX- Mud Bomb2.wav'],
    'Mud Shot': ['music/battle_anims/PRSFX- Mud Shot.wav'],
    'Mud-Slap': ['music/battle_anims/PRSFX- Mud Slap.wav'],
    'Mud Sport': ['music/battle_anims/PRSFX- Mud Sport1.wav', 'music/battle_anims/PRSFX- Mud Sport2.wav'],
    'Muddy Water': ['music/battle_anims/PRSFX- Muddy Water.wav'],
    'Multi-Attack': ['music/battle_anims/PRSFX- Multi Attack1.wav', 'music/battle_anims/PRSFX- Multi Attack2.wav', 'music/battle_anims/PRSFX- Multi Attack3.wav', 'music/battle_anims/PRSFX- Multi Attack4.wav', 'music/battle_anims/PRSFX- Multi Attack5.wav'],
    'Mystical Fire': ['music/battle_anims/PRSFX- Mystical Fire1.wav', 'music/battle_anims/PRSFX- Mystical Fire2.wav'],
    'Nasty Plot': ['music/battle_anims/PRSFX- Nasty Plot.wav'],
    'Natural Gift': ['music/battle_anims/PRSFX- Natural Gift1.wav', 'music/battle_anims/PRSFX- Natural Gift2.wav'],
    'Nature\'s Madness': ['music/battle_anims/PRSFX- Natures Madness1.wav', 'music/battle_anims/PRSFX- Natures Madness2.wav'],
    'Needle Arm': ['music/battle_anims/PRSFX- Needle Arm1.wav', 'music/battle_anims/PRSFX- Needle Arm2.wav'],
    'NeverEndingNightmare': ['music/battle_anims/PRSFX- NeverEndingNightmare1.wav', 'music/battle_anims/PRSFX- NeverEndingNightmare2.wav', 'music/battle_anims/PRSFX- NeverEndingNightmare3.wav', 'music/battle_anims/PRSFX- NeverEndingNightmare4.wav', 'music/battle_anims/PRSFX- NeverEndingNightmare5.wav', 'music/battle_anims/PRSFX- NeverEndingNightmare6.wav'],
    'Night Daze': ['music/battle_anims/PRSFX- Night Daze1.wav', 'music/battle_anims/PRSFX- Night Daze2.wav'],
    'Night Shade': ['music/battle_anims/PRSFX- Night Shade.wav'],
    'Night Slash': ['music/battle_anims/PRSFX- Night Slash1.wav', 'music/battle_anims/PRSFX- Night Slash2.wav'],
    'Nightmare': ['music/battle_anims/PRSFX- Nightmare.wav'],
    'Noble Roar': ['music/battle_anims/PRSFX- Noble Roar1.wav', 'music/battle_anims/PRSFX- Noble Roar2.wav'],
    'Nuzzle': ['music/battle_anims/PRSFX- Nuzzle1.wav', 'music/battle_anims/PRSFX- Nuzzle2.wav'],
    'Oblivion Wing': ['music/battle_anims/PRSFX- Oblivion Wing1.wav', 'music/battle_anims/PRSFX- Oblivion Wing2.wav'],
    'Oceanic Operetta': ['music/battle_anims/PRSFX- Oceanic Operetta1.wav', 'music/battle_anims/PRSFX- Oceanic Operetta2.wav', 'music/battle_anims/PRSFX- Oceanic Operetta3.wav', 'music/battle_anims/PRSFX- Oceanic Operetta4.wav'],
    'Octazooka': ['music/battle_anims/PRSFX- Octazooka.wav'],
    'Odor Sleuth': ['music/battle_anims/PRSFX- Odor Sleuth1.wav', 'music/battle_anims/PRSFX- Odor Sleuth2.wav'],
    'Ominous Wind': ['music/battle_anims/PRSFX- Ominous Wind.wav'],
    'Origin Pulse': ['music/battle_anims/PRSFX- Origin Pulse.wav', 'music/battle_anims/PRSFX- Origin Pulse1.wav', 'music/battle_anims/PRSFX- Origin Pulse2.wav', 'music/battle_anims/PRSFX- Origin Pulse3.wav'],
    'Outrage': ['music/battle_anims/PRSFX- Outrage1.wav', 'music/battle_anims/PRSFX- Outrage2.wav'],
    'Overheat': ['music/battle_anims/PRSFX- Overheat1.wav', 'music/battle_anims/PRSFX- Overheat2.wav'],
    'Pain Split': ['music/battle_anims/PRSFX- Pain Split.wav'],
    'Parabolic Charge': ['music/battle_anims/PRSFX- Parabolic Charge.wav'],
    'Paralysis': ['music/battle_anims/PRSFX- Paralysis.wav'],
    'Parting Shot': ['music/battle_anims/PRSFX- Parting Shot.wav'],
    'Pay Day': ['music/battle_anims/PRSFX- Pay Day1.wav', 'music/battle_anims/PRSFX- Pay Day2.wav'],
    'Payback': ['music/battle_anims/PRSFX- Payback1.wav', 'music/battle_anims/PRSFX- Payback2.wav'],
    'Peck': ['music/battle_anims/PRSFX- Peck.wav'],
    'Perish Song': ['music/battle_anims/PRSFX- Perish Song.wav'],
    'Petal Blizzard': ['music/battle_anims/PRSFX- Petal Blizzard1.wav', 'music/battle_anims/PRSFX- Petal Blizzard2.wav'],
    'Petal Dance': ['music/battle_anims/PRSFX- Petal Dance.wav'],
    'Phantom Force': ['music/battle_anims/PRSFX- Phantom Force1.wav', 'music/battle_anims/PRSFX- Phantom Force2.wav'],
    'Photon Geyser': ['music/battle_anims/PRSFX- Photon Guyser1.wav', 'music/battle_anims/PRSFX- Photon Guyser2.wav', 'music/battle_anims/PRSFX- Photon Guyser3.wav'],
    'Pin Missile': ['music/battle_anims/PRSFX- Pin Missile.wav'],
    'Plasma Fists': ['music/battle_anims/PRSFX- Plasma Fist1.wav', 'music/battle_anims/PRSFX- Plasma Fist2.wav', 'music/battle_anims/PRSFX- Plasma Fist3.wav'],
    'Play Nice': ['music/battle_anims/PRSFX- Play Nice1.wav', 'music/battle_anims/PRSFX- Play Nice2.wav'],
    'Play Rough': ['music/battle_anims/PRSFX- Play Rough1.wav', 'music/battle_anims/PRSFX- Play Rough2.wav', 'music/battle_anims/PRSFX- Play Rough3.wav', 'music/battle_anims/PRSFX- Play Rough4.wav'],
    'Pluck': ['music/battle_anims/PRSFX- Pluck1.wav', 'music/battle_anims/PRSFX- Pluck2.wav'],
    'Poison': ['music/battle_anims/PRSFX- Poison.wav'],
    'Poison Fang': ['music/battle_anims/PRSFX- Poison Fang1.wav', 'music/battle_anims/PRSFX- Poison Fang2.wav'],
    'Poison Gas': ['music/battle_anims/PRSFX- Poison Gas.wav'],
    'Poison Jab': ['music/battle_anims/PRSFX- Poison Jab1.wav', 'music/battle_anims/PRSFX- Poison Jab2.wav'],
    'Poison Powder': ['music/battle_anims/PRSFX- Poison Powder.wav'],
    'Poison Sting': ['music/battle_anims/PRSFX- Poison Sting.wav'],
    'Poison Tail': ['music/battle_anims/PRSFX- Poison Tail1.wav', 'music/battle_anims/PRSFX- Poison Tail2.wav'],
    'Pollen Puff': ['music/battle_anims/PRSFX- Pollen Puff1.wav', 'music/battle_anims/PRSFX- Pollen Puff2.wav', 'music/battle_anims/PRSFX- Pollen Puff3.wav', 'music/battle_anims/PRSFX- Pollen Puff4.wav', 'music/battle_anims/PRSFX- Pollen Puff5.wav', 'music/battle_anims/PRSFX- Pollen Puff6.wav'],
    'Pound': ['music/battle_anims/PRSFX- Pound.wav'],
    'Powder': ['music/battle_anims/PRSFX- Powder 1.wav', 'music/battle_anims/PRSFX- Powder 2.wav'],
    'Powder common': ['music/battle_anims/PRSFX- Powder common1.wav', 'music/battle_anims/PRSFX- Powder common2.wav'],
    'Powder Snow': ['music/battle_anims/PRSFX- Powder Snow1.wav', 'music/battle_anims/PRSFX- Powder Snow2.wav'],
    'Power Gem': ['music/battle_anims/PRSFX- Power Gem1.wav'],
    'Power Split': ['music/battle_anims/PRSFX- Power Split.wav'],
    'Power Swap': ['music/battle_anims/PRSFX- Power Swap.wav'],
    'Power Trick': ['music/battle_anims/PRSFX- Power Trick.wav'],
    'Power Trip': ['music/battle_anims/PRSFX- Power Trip1.wav', 'music/battle_anims/PRSFX- Power Trip2.wav', 'music/battle_anims/PRSFX- Power Trip3.wav', 'music/battle_anims/PRSFX- Power Trip4.wav', 'music/battle_anims/PRSFX- Power Trip5.wav'],
    'Power-Up Punch': ['music/battle_anims/PRSFX- Power Up Punch1.wav', 'music/battle_anims/PRSFX- Power Up Punch2.wav'],
    'Power Whip': ['music/battle_anims/PRSFX- Power Whip.wav'],
    'Precipice Blades': ['music/battle_anims/PRSFX- Precipice Blades.wav'],
    'Present': ['music/battle_anims/PRSFX- Present1.wav', 'music/battle_anims/PRSFX- Present2.wav'],
    'Prismatic Laser': ['music/battle_anims/PRSFX- Prismatic Laser1.wav', 'music/battle_anims/PRSFX- Prismatic Laser2.wav', 'music/battle_anims/PRSFX- Prismatic Laser3.wav'],
    'Protect': ['music/battle_anims/PRSFX- Protect.wav'],
    'Psybeam': ['music/battle_anims/PRSFX- Psybeam.wav'],
    'Psych Up': ['music/battle_anims/PRSFX- Psych Up.wav'],
    'Psychic': ['music/battle_anims/PRSFX- Psychic.wav'],
    'Psychic Terrain': ['music/battle_anims/PRSFX- Psychic Terrain1.wav', 'music/battle_anims/PRSFX- Psychic Terrain2.wav', 'music/battle_anims/PRSFX- Psychic Terrain3.wav'],
    'Psycho Boost': ['music/battle_anims/PRSFX- Psycho Boost1.wav', 'music/battle_anims/PRSFX- Psycho Boost2.wav'],
    'Psycho Cut': ['music/battle_anims/PRSFX- Psycho Cut.wav'],
    'Psycho Shift': ['music/battle_anims/PRSFX- Psycho Shift.wav'],
    'Psyshock': ['music/battle_anims/PRSFX- Psyshock1.wav', 'music/battle_anims/PRSFX- Psyshock2.wav'],
    'Psystrike': ['music/battle_anims/PRSFX- Psystrike1.wav', 'music/battle_anims/PRSFX- Psystrike2.wav', 'music/battle_anims/PRSFX- Psystrike3.wav'],
    'Psywave': ['music/battle_anims/PRSFX- Psywave.wav'],
    'Pulse Evolution': ['music/battle_anims/PRSFX- Pulse Evolution1.wav', 'music/battle_anims/PRSFX- Pulse Evolution2.wav'],
    'Pulverizing Pancake': ['music/battle_anims/PRSFX- Pulverizing Pancake1.wav', 'music/battle_anims/PRSFX- Pulverizing Pancake2.wav', 'music/battle_anims/PRSFX- Pulverizing Pancake3.wav', 'music/battle_anims/PRSFX- Pulverizing Pancake4.wav', 'music/battle_anims/PRSFX- Pulverizing Pancake5.wav'],
    'Punishment': ['music/battle_anims/PRSFX- Punishment1.wav', 'music/battle_anims/PRSFX- Punishment2.wav'],
    'Purify': ['music/battle_anims/PRSFX- Purify1.wav', 'music/battle_anims/PRSFX- Purify2.wav', 'music/battle_anims/PRSFX- Purify3.wav'],
    'Pursuit': ['music/battle_anims/PRSFX- Pursuit1.wav', 'music/battle_anims/PRSFX- Pursuit2.wav'],
    'Quash': ['music/battle_anims/PRSFX- Quash.wav'],
    'Quick Attack': ['music/battle_anims/PRSFX- Quick Attack.wav'],
    'Quick Guard': ['music/battle_anims/PRSFX- Quick Guard.wav'],
    'Quiver Dance': ['music/battle_anims/PRSFX- Quiver Dance.wav'],
    'Rage': ['music/battle_anims/PRSFX- Rage1.wav', 'music/battle_anims/PRSFX- Rage2.wav'],
    'Rage Powder': ['music/battle_anims/PRSFX- Rage Powder.wav'],
    'Rain': ['music/battle_anims/PRSFX- Rain.wav'],
    'Rain Dance': ['music/battle_anims/PRSFX- Rain Dance.wav'],
    'Rainbow Field': ['music/battle_anims/PRSFX- Rainbow Field.wav'],
    'Rapid Spin': ['music/battle_anims/PRSFX- Rapid Spin.wav'],
    'Razor Leaf': ['music/battle_anims/PRSFX- Razor Leaf1.wav', 'music/battle_anims/PRSFX- Razor Leaf2.wav'],
    'Razor Shell': ['music/battle_anims/PRSFX- Razor Shell.wav'],
    'Razor Wind': ['music/battle_anims/PRSFX- Razor Wind1.wav', 'music/battle_anims/PRSFX- Razor Wind2.wav'],
    'Recover': ['music/battle_anims/PRSFX- Recover.wav'],
    'Recycle': ['music/battle_anims/PRSFX- Recycle.wav'],
    'Reflect': ['music/battle_anims/PRSFX- Reflect.wav'],
    'Reflect Type': ['music/battle_anims/PRSFX- Reflect Type.wav'],
    'Refresh': ['music/battle_anims/PRSFX- Refresh.wav'],
    'Relic Song': ['music/battle_anims/PRSFX- Relic Song1.wav', 'music/battle_anims/PRSFX- Relic Song2.wav'],
    'Retaliate': ['music/battle_anims/PRSFX- Retaliate1.wav', 'music/battle_anims/PRSFX- Retaliate2.wav'],
    'Return': ['music/battle_anims/PRSFX- Return1.wav', 'music/battle_anims/PRSFX- Return2.wav'],
    'Revenge': ['music/battle_anims/PRSFX- Revenge1.wav', 'music/battle_anims/PRSFX- Revenge2.wav'],
    'Reversal': ['music/battle_anims/PRSFX- Reversal1.wav', 'music/battle_anims/PRSFX- Reversal2.wav'],
    'Roar': ['music/battle_anims/PRSFX- Roar.wav'],
    'Roar of Time': ['music/battle_anims/PRSFX- Roar of Time.wav'],
    'Rock Blast': ['music/battle_anims/PRSFX- Rock Blast.wav'],
    'Rock Climb': ['music/battle_anims/PRSFX- Rock Climb.wav'],
    'Rock Polish': ['music/battle_anims/PRSFX- Rock Polish.wav'],
    'Rock Slide': ['music/battle_anims/PRSFX- Rock Slide.wav'],
    'Rock Smash': ['music/battle_anims/PRSFX- Rock Smash.wav'],
    'Rock Throw': ['music/battle_anims/PRSFX- Rock Throw1.wav', 'music/battle_anims/PRSFX- Rock Throw2.wav'],
    'Rock Tomb': ['music/battle_anims/PRSFX- Rock Tomb.wav'],
    'Rock Wrecker': ['music/battle_anims/PRSFX- Rock Wrecker1.wav', 'music/battle_anims/PRSFX- Rock Wrecker2.wav'],
    'Role Play': ['music/battle_anims/PRSFX- Roleplay.wav'],
    'Rolling Kick': ['music/battle_anims/PRSFX- Rolling Kick.wav'],
    'Rollout': ['music/battle_anims/PRSFX- Rollout1.wav', 'music/battle_anims/PRSFX- Rollout2.wav'],
    'Roost': ['music/battle_anims/PRSFX- Roost1.wav', 'music/battle_anims/PRSFX- Roost2.wav'],
    'Rototiller': ['music/battle_anims/PRSFX- Rototiller.wav'],
    'Round': ['music/battle_anims/PRSFX- Round.wav'],
    'Sacred Fire': ['music/battle_anims/PRSFX- Sacred Fire1.wav', 'music/battle_anims/PRSFX- Sacred Fire2.wav'],
    'Sacred Sword': ['music/battle_anims/PRSFX- Sacred Sword1.wav', 'music/battle_anims/PRSFX- Sacred Sword2.wav'],
    'Safeguard': ['music/battle_anims/PRSFX- Safeguard.wav'],
    'Sand': ['music/battle_anims/PRSFX- Sand.wav'],
    'Sand Attack': ['music/battle_anims/PRSFX- Sand Attack.wav'],
    'Sand Tomb': ['music/battle_anims/PRSFX- Sand Tomb.wav'],
    'Sandstorm': ['music/battle_anims/PRSFX- Sandstorm.wav'],
    'Scald': ['music/battle_anims/PRSFX- Scald1.wav', 'music/battle_anims/PRSFX- Scald2.wav'],
    'Scary Face': ['music/battle_anims/PRSFX- Scary Face.wav'],
    'Scratch': ['music/battle_anims/PRSFX- Scratch.wav'],
    'Screech': ['music/battle_anims/PRSFX- Screech.wav'],
    'Searing Shot': ['music/battle_anims/PRSFX- Searing Shot1.wav', 'music/battle_anims/PRSFX- Searing Shot2.wav', 'music/battle_anims/PRSFX- Searing Shot3.wav'],
    'Secret Sword': ['music/battle_anims/PRSFX- Secret Sword1.wav', 'music/battle_anims/PRSFX- Secret Sword2.wav', 'music/battle_anims/PRSFX- Secret Sword3.wav'],
    'Seed Bomb': ['music/battle_anims/PRSFX- Seed Bomb1.wav', 'music/battle_anims/PRSFX- Seed Bomb2.wav'],
    'Seed Flare': ['music/battle_anims/PRSFX- Seed Flare1.wav', 'music/battle_anims/PRSFX- Seed Flare2.wav', 'music/battle_anims/PRSFX- Seed Flare3.wav'],
    'Seismic Toss': ['music/battle_anims/PRSFX- Seismic Toss1.wav', 'music/battle_anims/PRSFX- Seismic Toss2.wav', 'music/battle_anims/PRSFX- Seismic Toss3.wav', 'music/battle_anims/PRSFX- Seismic Toss4.wav', 'music/battle_anims/PRSFX- Seismic Toss5.wav'],
    'Self-Destruct': ['music/battle_anims/PRSFX- Selfdestruct1.wav'],
    'Selfedestruct': ['music/battle_anims/PRSFX- Selfedestruct2.wav'],
    'Shadow Ball': ['music/battle_anims/PRSFX- Shadow Ball1.wav', 'music/battle_anims/PRSFX- Shadow Ball2.wav'],
    'Shadow Claw': ['music/battle_anims/PRSFX- Shadow Claw1.wav', 'music/battle_anims/PRSFX- Shadow Claw2.wav'],
    'Shadow Force': ['music/battle_anims/PRSFX- Shadow Force1.wav', 'music/battle_anims/PRSFX- Shadow Force2.wav'],
    'Shadow Punch': ['music/battle_anims/PRSFX- Shadow Punch1.wav', 'music/battle_anims/PRSFX- Shadow Punch2.wav'],
    'Shadow Sneak': ['music/battle_anims/PRSFX- Shadow Sneak1.wav', 'music/battle_anims/PRSFX- Shadow Sneak2.wav'],
    'Shadow Bone': ['music/battle_anims/PRSFX- ShadowBone1.wav', 'music/battle_anims/PRSFX- ShadowBone2.wav'],
    'Sharpen': ['music/battle_anims/PRSFX- Sharpen.wav'],
    'Shattered Psyche': ['music/battle_anims/PRSFX- Shattered Psyche1.wav', 'music/battle_anims/PRSFX- Shattered Psyche2.wav', 'music/battle_anims/PRSFX- Shattered Psyche3.wav'],
    'Sheer Cold': ['music/battle_anims/PRSFX- Sheer Cold.wav'],
    'Shell Smash': ['music/battle_anims/PRSFX- Shell Smash1.wav', 'music/battle_anims/PRSFX- Shell Smash2.wav'],
    'Shell Trap': ['music/battle_anims/PRSFX- Shell Trap1.wav', 'music/battle_anims/PRSFX- Shell Trap2.wav', 'music/battle_anims/PRSFX- Shell Trap3.wav'],
    'Shift Gear': ['music/battle_anims/PRSFX- Shift Gear.wav'],
    'Shiny': ['music/battle_anims/PRSFX- Shiny.wav'],
    'Shock Wave': ['music/battle_anims/PRSFX- Shockwave.wav'],
    'Shore Up': ['music/battle_anims/PRSFX- Shore Up.wav'],
    'Signal Beam': ['music/battle_anims/PRSFX- Signal Beam.wav'],
    'Silver Wind': ['music/battle_anims/PRSFX- Silver Wind.wav'],
    'Simple Beam': ['music/battle_anims/PRSFX- Simple Beam.wav'],
    'Sing': ['music/battle_anims/PRSFX- Sing.wav'],
    'SinisterArrowRaid': ['music/battle_anims/PRSFX- SinisterArrowRaid1.wav', 'music/battle_anims/PRSFX- SinisterArrowRaid2.wav', 'music/battle_anims/PRSFX- SinisterArrowRaid3.wav', 'music/battle_anims/PRSFX- SinisterArrowRaid4.wav', 'music/battle_anims/PRSFX- SinisterArrowRaid5.wav'],
    'Sketch': ['music/battle_anims/PRSFX- Sketch.wav'],
    'Skill Swap': ['music/battle_anims/PRSFX- Skill Swap.wav'],
    'Skull Bash': ['music/battle_anims/PRSFX- Skull Bash1.wav', 'music/battle_anims/PRSFX- Skull Bash2.wav'],
    'Sky Attack': ['music/battle_anims/PRSFX- Sky Attack1.wav', 'music/battle_anims/PRSFX- Sky Attack2.wav', 'music/battle_anims/PRSFX- Sky Attack3.wav'],
    'Sky Drop': ['music/battle_anims/PRSFX- Sky Drop1.wav', 'music/battle_anims/PRSFX- Sky Drop2.wav', 'music/battle_anims/PRSFX- Sky Drop3.wav'],
    'Sky Uppercut': ['music/battle_anims/PRSFX- Sky Uppercut1.wav', 'music/battle_anims/PRSFX- Sky Uppercut2.wav'],
    'Slack Off': ['music/battle_anims/PRSFX- Slack Off.wav'],
    'Slam': ['music/battle_anims/PRSFX- Slam.wav'],
    'Slash': ['music/battle_anims/PRSFX- Slash.wav'],
    'Sleep': ['music/battle_anims/PRSFX- Sleep.wav'],
    'Sleep Powder': ['music/battle_anims/PRSFX- Sleep Powder.wav'],
    'Sleep Talk': ['music/battle_anims/PRSFX- Sleep Talk.wav'],
    'Sludge': ['music/battle_anims/PRSFX- Sludge.wav'],
    'Sludge Bomb': ['music/battle_anims/PRSFX- Sludge Bomb1.wav', 'music/battle_anims/PRSFX- Sludge Bomb2.wav'],
    'Sludge Wave': ['music/battle_anims/PRSFX- Sludge Wave.wav'],
    'Smack Down': ['music/battle_anims/PRSFX- Smack Down1.wav', 'music/battle_anims/PRSFX- Smack Down2.wav', 'music/battle_anims/PRSFX- Smack Down3.wav'],
    'Smart Strike': ['music/battle_anims/PRSFX- Smart Strike1.wav', 'music/battle_anims/PRSFX- Smart Strike2.wav', 'music/battle_anims/PRSFX- Smart Strike3.wav', 'music/battle_anims/PRSFX- Smart Strike4.wav'],
    'Smelling Salts': ['music/battle_anims/PRSFX- Smellingsalts.wav'],
    'Smog': ['music/battle_anims/PRSFX- Smog.wav'],
    'Smokescreen': ['music/battle_anims/PRSFX- Smokescreen.wav'],
    'Snarl': ['music/battle_anims/PRSFX- Snarl.wav'],
    'Snatch': ['music/battle_anims/PRSFX- Snatch.wav'],
    'Snore': ['music/battle_anims/PRSFX- Snore.wav'],
    'Soak': ['music/battle_anims/PRSFX- Soak.wav'],
    'Soft-Boiled': ['music/battle_anims/PRSFX- Softboiled1.wav', 'music/battle_anims/PRSFX- Softboiled2.wav', 'music/battle_anims/PRSFX- Softboiled3.wav'],
    'Solar Beam': ['music/battle_anims/PRSFX- Solar Beam1.wav', 'music/battle_anims/PRSFX- Solar Beam2.wav'],
    'Sonic Boom': ['music/battle_anims/PRSFX- Sonic Boom1.wav', 'music/battle_anims/PRSFX- Sonic Boom2.wav'],
    'Spacial Rend': ['music/battle_anims/PRSFX- Spacial Rend.wav'],
    'Spark': ['music/battle_anims/PRSFX- Spark1.wav', 'music/battle_anims/PRSFX- Spark2.wav'],
    'Sparkling Aria': ['music/battle_anims/PRSFX- Sparkling Aria1.wav', 'music/battle_anims/PRSFX- Sparkling Aria2.wav', 'music/battle_anims/PRSFX- Sparkling Aria3.wav'],
    'Spectral Thief': ['music/battle_anims/PRSFX- Spectral Thief1.wav', 'music/battle_anims/PRSFX- Spectral Thief2.wav', 'music/battle_anims/PRSFX- Spectral Thief3.wav', 'music/battle_anims/PRSFX- Spectral Thief4.wav'],
    'Speed Swap': ['music/battle_anims/PRSFX- Speed Swap.wav'],
    'Spider Web': ['music/battle_anims/PRSFX- Spider Web1.wav', 'music/battle_anims/PRSFX- Spider Web2.wav'],
    'Spike Cannon': ['music/battle_anims/PRSFX- Spike Cannon.wav'],
    'Spikes': ['music/battle_anims/PRSFX- Spikes1.wav', 'music/battle_anims/PRSFX- Spikes2.wav'],
    'Spiky Shield': ['music/battle_anims/PRSFX- Spiky Shield1.wav', 'music/battle_anims/PRSFX- Spiky Shield2.wav'],
    'Spirit Shackle': ['music/battle_anims/PRSFX- Spirit Shackle1.wav', 'music/battle_anims/PRSFX- Spirit Shackle2.wav', 'music/battle_anims/PRSFX- Spirit Shackle3.wav', 'music/battle_anims/PRSFX- Spirit Shackle4.wav'],
    'Spit Up': ['music/battle_anims/PRSFX- Spit Up.wav'],
    'Spite': ['music/battle_anims/PRSFX- Spite1.wav', 'music/battle_anims/PRSFX- Spite2.wav'],
    'Splash': ['music/battle_anims/PRSFX- Splash.wav'],
    'Spore': ['music/battle_anims/PRSFX- Spore.wav'],
    'Spotlight': ['music/battle_anims/PRSFX- Spotlight1.wav', 'music/battle_anims/PRSFX- Spotlight2.wav', 'music/battle_anims/PRSFX- Spotlight3.wav', 'music/battle_anims/PRSFX- Spotlight4.wav', 'music/battle_anims/PRSFX- Spotlight5.wav'],
    'Stat Down': ['music/battle_anims/PRSFX- Stat Down.wav'],
    'Stat Up': ['music/battle_anims/PRSFX- Stat Up.wav'],
    'Stealth Rock': ['music/battle_anims/PRSFX- Stealth Rocks.wav'],
    'Steam Eruption': ['music/battle_anims/PRSFX- Steam Eruption1.wav', 'music/battle_anims/PRSFX- Steam Eruption2.wav'],
    'Steamroller': ['music/battle_anims/PRSFX- Steamroller1.wav', 'music/battle_anims/PRSFX- Steamroller2.wav'],
    'Steel Wing': ['music/battle_anims/PRSFX- Steel Wing.wav'],
    'Sticky Web': ['music/battle_anims/PRSFX- Sticky Web.wav'],
    'Stockpile': ['music/battle_anims/PRSFX- Stockpile.wav'],
    'Stomp': ['music/battle_anims/PRSFX- Stomp.wav'],
    'Stomping Tantrum': ['music/battle_anims/PRSFX- Stomping Tantrum.wav'],
    'Stone Edge': ['music/battle_anims/PRSFX- Stone Edge.wav'],
    'Stored Power': ['music/battle_anims/PRSFX- Stored Power1.wav', 'music/battle_anims/PRSFX- Stored Power2.wav'],
    'Storm Throw': ['music/battle_anims/PRSFX- Storm Throw1.wav', 'music/battle_anims/PRSFX- Storm Throw2.wav'],
    'Strength': ['music/battle_anims/PRSFX- Strength.wav'],
    'Strength Sap': ['music/battle_anims/PRSFX- Strength Sap1.wav', 'music/battle_anims/PRSFX- Strength Sap2.wav', 'music/battle_anims/PRSFX- Strength Sap3.wav'],
    'String Shot': ['music/battle_anims/PRSFX- String Shot1.wav', 'music/battle_anims/PRSFX- String Shot2.wav'],
    'Struggle': ['music/battle_anims/PRSFX- Struggle.wav'],
    'Struggle Bug': ['music/battle_anims/PRSFX- Struggle Bug.wav'],
    'Stun Spore': ['music/battle_anims/PRSFX- Stun Spore.wav'],
    'Submission': ['music/battle_anims/PRSFX- Submission.wav'],
    'Substitute': ['music/battle_anims/PRSFX- Substitute1.wav', 'music/battle_anims/PRSFX- Substitute2.wav'],
    'Subzero Slammer': ['music/battle_anims/PRSFX- Subzero Slammer1.wav', 'music/battle_anims/PRSFX- Subzero Slammer2.wav', 'music/battle_anims/PRSFX- Subzero Slammer3.wav', 'music/battle_anims/PRSFX- Subzero Slammer4.wav'],
    'Sucker Punch': ['music/battle_anims/PRSFX- Sucker Punch1.wav', 'music/battle_anims/PRSFX- Sucker Punch2.wav'],
    'Sunny': ['music/battle_anims/PRSFX- Sunny.wav'],
    'Sunny Day': ['music/battle_anims/PRSFX- Sunny Day.wav'],
    'Super Fang': ['music/battle_anims/PRSFX- Super Fang1.wav', 'music/battle_anims/PRSFX- Super Fang2.wav'],
    'Superpower': ['music/battle_anims/PRSFX- Superpower1.wav', 'music/battle_anims/PRSFX- Superpower2.wav'],
    'Supersonic': ['music/battle_anims/PRSFX- Supersonic.wav'],
    'Surf': ['music/battle_anims/PRSFX- Surf.wav'],
    'Swagger': ['music/battle_anims/PRSFX- Swagger1.wav', 'music/battle_anims/PRSFX- Swagger2.wav'],
    'Swallow': ['music/battle_anims/PRSFX- Swallow.wav'],
    'Sweet Kiss': ['music/battle_anims/PRSFX- Sweet Kiss1.wav', 'music/battle_anims/PRSFX- Sweet Kiss2.wav'],
    'Sweet Scent': ['music/battle_anims/PRSFX- Sweet Scent.wav'],
    'Swift': ['music/battle_anims/PRSFX- Swift1.wav', 'music/battle_anims/PRSFX- Swift2.wav'],
    'Switcheroo': ['music/battle_anims/PRSFX- Switcheroo.wav'],
    'Swords Dance': ['music/battle_anims/PRSFX- Swords Dance1.wav', 'music/battle_anims/PRSFX- Swords Dance2.wav'],
    'Synchronoise': ['music/battle_anims/PRSFX- Synchronoise.wav'],
    'Synthesis': ['music/battle_anims/PRSFX- Synthesis.wav'],
    'Tackle': ['music/battle_anims/PRSFX- Tackle.wav'],
    'Tail Glow': ['music/battle_anims/PRSFX- Tail Glow.wav'],
    'Tail Slap': ['music/battle_anims/PRSFX- Tail Slap.wav'],
    'Tail Whip': ['music/battle_anims/PRSFX- Tail Whip.wav'],
    'Tailwind': ['music/battle_anims/PRSFX- Tailwind.wav'],
    'Take Down': ['music/battle_anims/PRSFX- Take Down1.wav', 'music/battle_anims/PRSFX- Take Down2.wav'],
    'Taunt': ['music/battle_anims/PRSFX- Taunt1.wav', 'music/battle_anims/PRSFX- Taunt2.wav', 'music/battle_anims/PRSFX- Taunt3.wav'],
    'Tearful Look': ['music/battle_anims/PRSFX- Tearful Look1.wav', 'music/battle_anims/PRSFX- Tearful Look2.wav', 'music/battle_anims/PRSFX- Tearful Look3.wav'],
    'Techno Blast': ['music/battle_anims/PRSFX- Techno Blast 1.wav', 'music/battle_anims/PRSFX- Techno Blast 2.wav', 'music/battle_anims/PRSFX- Techno Blast 3.wav'],
    'Teeter Dance': ['music/battle_anims/PRSFX- Teeter Dance.wav'],
    'Telekinesis': ['music/battle_anims/PRSFX- Telekinesis.wav'],
    'Teleport': ['music/battle_anims/PRSFX- Teleport.wav'],
    'Thief': ['music/battle_anims/PRSFX- Theif1.wav', 'music/battle_anims/PRSFX- Theif2.wav'],
    'Thousand Arrows': ['music/battle_anims/PRSFX- Thousand Arrows1.wav', 'music/battle_anims/PRSFX- Thousand Arrows2.wav'],
    'Thousand Waves': ['music/battle_anims/PRSFX- Thousand Waves1.wav', 'music/battle_anims/PRSFX- Thousand Waves2.wav'],
    'Thrash': ['music/battle_anims/PRSFX- Thrash.wav', 'music/battle_anims/PRSFX- Thrash2.wav'],
    'Throat Chop': ['music/battle_anims/PRSFX- Throat Chop1.wav', 'music/battle_anims/PRSFX- Throat Chop2.wav', 'music/battle_anims/PRSFX- Throat Chop3.wav', 'music/battle_anims/PRSFX- Throat Chop4.wav', 'music/battle_anims/PRSFX- Throat Chop5.wav'],
    'Thunder': ['music/battle_anims/PRSFX- Thunder.wav'],
    'Thunder Fang': ['music/battle_anims/PRSFX- Thunder Fang.wav'],
    'Thunder Punch': ['music/battle_anims/PRSFX- Thunder Punch1.wav', 'music/battle_anims/PRSFX- Thunder Punch2.wav'],
    'Thunder Wave': ['music/battle_anims/PRSFX- Thunder Wave.wav'],
    'Thunderbolt': ['music/battle_anims/PRSFX- Thunderbolt1.wav', 'music/battle_anims/PRSFX- Thunderbolt2.wav'],
    'Thunder Shock': ['music/battle_anims/PRSFX- Thundershock.wav'],
    'Tickle': ['music/battle_anims/PRSFX- Tickle.wav'],
    'Topsy-Turvy': ['music/battle_anims/PRSFX- Topsy Turvy.wav'],
    'Torment': ['music/battle_anims/PRSFX- Torment1.wav', 'music/battle_anims/PRSFX- Torment2.wav'],
    'Toxic': ['music/battle_anims/PRSFX- Toxic1.wav', 'music/battle_anims/PRSFX- Toxic2.wav'],
    'Toxic Spikes': ['music/battle_anims/PRSFX- Toxic Spikes1.wav', 'music/battle_anims/PRSFX- Toxic Spikes2.wav'],
    'Toxic Thread': ['music/battle_anims/PRSFX- Toxic Thread1.wav', 'music/battle_anims/PRSFX- Toxic Thread2.wav', 'music/battle_anims/PRSFX- Toxic Thread3.wav'],
    'Trainer': ['music/battle_anims/PRSFX- Trainer.wav'],
    'Transform': ['music/battle_anims/PRSFX- Transform.wav'],
    'Tri Attack': ['music/battle_anims/PRSFX- Tri Attack.wav'],
    'Trick': ['music/battle_anims/PRSFX- Trick.wav'],
    'Trick-or-Treat': ['music/battle_anims/PRSFX- Trick or Treat.wav'],
    'Trick Room': ['music/battle_anims/PRSFX- Trick Room.wav'],
    'Triple Kick': ['music/battle_anims/PRSFX- Triple Kick.wav'],
    'Trop Kick': ['music/battle_anims/PRSFX- Trop Kick1.wav', 'music/battle_anims/PRSFX- Trop Kick2.wav', 'music/battle_anims/PRSFX- Trop Kick3.wav'],
    'Trump Card': ['music/battle_anims/PRSFX- Trump Card1.wav', 'music/battle_anims/PRSFX- Trump Card2.wav'],
    'Twineedle': ['music/battle_anims/PRSFX- Twineedle1.wav', 'music/battle_anims/PRSFX- Twineedle2.wav'],
    'Twinkle Tackle': ['music/battle_anims/PRSFX- Twinkle Tackle1.wav', 'music/battle_anims/PRSFX- Twinkle Tackle2.wav', 'music/battle_anims/PRSFX- Twinkle Tackle3.wav'],
    'Twister': ['music/battle_anims/PRSFX- Twister.wav'],
    'Uproar': ['music/battle_anims/PRSFX- Uproar1.wav', 'music/battle_anims/PRSFX- Uproar2.wav'],
    'U-turn': ['music/battle_anims/PRSFX- U-Turn.wav', 'music/battle_anims/PRSFX- U-Turn2.wav'],
    'Vacuum Wave': ['music/battle_anims/PRSFX- Vacuum Wave1.wav', 'music/battle_anims/PRSFX- Vacuum Wave2.wav'],
    'V-create': ['music/battle_anims/PRSFX- V-Create1.wav', 'music/battle_anims/PRSFX- V-Create2.wav'],
    'Venom Drench': ['music/battle_anims/PRSFX- Venom Drench.wav'],
    'Venoshock': ['music/battle_anims/PRSFX- Venoshock1.wav', 'music/battle_anims/PRSFX- Venoshock2.wav'],
    'Vise Grip': ['music/battle_anims/PRSFX- Vice Grip.wav'],
    'Vine Whip': ['music/battle_anims/PRSFX- Vine Whip.wav'],
    'Vital Throw': ['music/battle_anims/PRSFX- Vital Throw1.wav', 'music/battle_anims/PRSFX- Vital Throw2.wav'],
    'Volt Switch': ['music/battle_anims/PRSFX- Volt Switch1.wav', 'music/battle_anims/PRSFX- Volt Switch2.wav'],
    'Volt Tackle': ['music/battle_anims/PRSFX- Volt Tackle1.wav', 'music/battle_anims/PRSFX- Volt Tackle2.wav'],
    'Wake-Up Slap': ['music/battle_anims/PRSFX- Wake Up Slap.wav'],
    'Water Gun': ['music/battle_anims/PRSFX- Water Gun.wav'],
    'Water Pledge': ['music/battle_anims/PRSFX- Water Pledge1.wav', 'music/battle_anims/PRSFX- Water Pledge2.wav'],
    'Water Pulse': ['music/battle_anims/PRSFX- Water Pulse.wav', 'music/battle_anims/PRSFX- Water Pulse2.wav'],
    'Water Shuriken': ['music/battle_anims/PRSFX- Water Shurkein.wav'],
    'Water Sport': ['music/battle_anims/PRSFX- Water Sport.wav'],
    'Water Spout': ['music/battle_anims/PRSFX- Water Spout1.wav', 'music/battle_anims/PRSFX- Water Spout2.wav'],
    'Waterfall': ['music/battle_anims/PRSFX- Waterfall1.wav', 'music/battle_anims/PRSFX- Waterfall2.wav'],
    'Weather Ball': ['music/battle_anims/PRSFX- Weather Ball1.wav', 'music/battle_anims/PRSFX- Weather Ball2.wav', 'music/battle_anims/PRSFX- Weather Ball3.wav', 'music/battle_anims/PRSFX- Weather Ball4.wav', 'music/battle_anims/PRSFX- Weather Ball5.wav', 'music/battle_anims/PRSFX- Weather Ball6.wav'],
    'Whirlpool': ['music/battle_anims/PRSFX- Whirlpool.wav', 'music/battle_anims/PRSFX- Whirlpool2.wav'],
    'Whirlwind': ['music/battle_anims/PRSFX- Whirlwind.wav'],
    'Wide Guard': ['music/battle_anims/PRSFX- Wide Guard.wav'],
    'Wild Charge': ['music/battle_anims/PRSFX- Wild Charge1.wav', 'music/battle_anims/PRSFX- Wild Charge2.wav'],
    'Will-O-Wisp': ['music/battle_anims/PRSFX- Will O Wisp1.wav', 'music/battle_anims/PRSFX- Will O Wisp2.wav'],
    'Wind': ['music/battle_anims/PRSFX- Wind.wav'],
    'Wing Attack': ['music/battle_anims/PRSFX- Wing Attack1.wav', 'music/battle_anims/PRSFX- Wing Attack2.wav'],
    'Wish': ['music/battle_anims/PRSFX- Wish.wav', 'music/battle_anims/PRSFX- Wish2.wav'],
    'Withdraw': ['music/battle_anims/PRSFX- Withdraw.wav'],
    'Wonder Room': ['music/battle_anims/PRSFX- Wonder Room.wav'],
    'Wood Hammer': ['music/battle_anims/PRSFX- Wood Hammer.wav'],
    'Work Up': ['music/battle_anims/PRSFX- Work Up.wav'],
    'Worry Seed': ['music/battle_anims/PRSFX- Worry Seed1.wav', 'music/battle_anims/PRSFX- Worry Seed2.wav'],
    'Wrap': ['music/battle_anims/PRSFX- Wrap.wav'],
    'Wring Out': ['music/battle_anims/PRSFX- Wring Out1.wav', 'music/battle_anims/PRSFX- Wring Out2.wav'],
    'X-Scissor': ['music/battle_anims/PRSFX- X Scissor.wav'],
    'Yawn': ['music/battle_anims/PRSFX- Yawn.wav'],
    'Zap Cannon': ['music/battle_anims/PRSFX- Zap Cannon1.wav', 'music/battle_anims/PRSFX- Zap Cannon2.wav', 'music/battle_anims/PRSFX- Zap Cannon3.wav'],
    'Zen Headbutt': ['music/battle_anims/PRSFX- Zen Headbutt1.wav', 'music/battle_anims/PRSFX- Zen Headbutt2.wav'],
    'Zing Zap': ['music/battle_anims/PRSFX- Zing Zap1.wav', 'music/battle_anims/PRSFX- Zing Zap2.wav', 'music/battle_anims/PRSFX- Zing Zap3.wav', 'music/battle_anims/PRSFX- Zing Zap4.wav'],
    'Zpower': ['music/battle_anims/PRSFX- Zpower1.wav', 'music/battle_anims/PRSFX- ZPower2.wav', 'music/battle_anims/PRSFX- ZPower3.wav'],
    'First Impression': ['music/battle_anims/PRSFX- Attack Order1.wav', 'music/battle_anims/PRSFX- Attack Order2.wav'],
    'G-Max Befuddle': ['music/battle_anims/PRSFX- Pin Missile.wav'],
    'Lunge': ['music/battle_anims/PRSFX- Leech Life1.wav', 'music/battle_anims/PRSFX- Leech Life2.wav'],
    'Max Flutterby': ['music/battle_anims/PRSFX- Pin Missile.wav'],
    'Pounce': ['music/battle_anims/PRSFX- Fell Stinger1.wav', 'music/battle_anims/PRSFX- Fell Stinger2.wav', 'music/battle_anims/PRSFX- Fell Stinger3.wav'],
    'Savage Spin-Out': ['music/battle_anims/PRSFX- Pin Missile.wav'],
    'Skitter Smack': ['music/battle_anims/PRSFX- U-Turn.wav', 'music/battle_anims/PRSFX- U-Turn2.wav'],
    'Hidden Power Bug': ['music/battle_anims/PRSFX- Silver Wind.wav'],
    'Silk Trap': ['music/battle_anims/PRSFX- Defend Order1.wav', 'music/battle_anims/PRSFX- Defend Order2.wav'],
    'Ceaseless Edge': ['music/battle_anims/PRSFX- Knock Off.wav'],
    'Comeuppance': ['music/battle_anims/PRSFX- Beat Up.wav'],
    'Darkest Lariat': ['music/battle_anims/PRSFX- Crunch.wav'],
    'False Surrender': ['music/battle_anims/PRSFX- Crunch.wav'],
    'G-Max One Blow': ['music/battle_anims/PRSFX- Black Hole Eclipse1.wav', 'music/battle_anims/PRSFX- Black Hole Eclipse2.wav', 'music/battle_anims/PRSFX- Black Hole Eclipse3.wav', 'music/battle_anims/PRSFX- Black Hole Eclipse4.wav'],
    'G-Max Snooze': ['music/battle_anims/PRSFX- Black Hole Eclipse1.wav', 'music/battle_anims/PRSFX- Black Hole Eclipse2.wav', 'music/battle_anims/PRSFX- Black Hole Eclipse3.wav', 'music/battle_anims/PRSFX- Black Hole Eclipse4.wav'],
    'Jaw Lock': ['music/battle_anims/PRSFX- Crunch.wav'],
    'Kowtow Cleave': ['music/battle_anims/PRSFX- Crunch.wav'],
    'Lash Out': ['music/battle_anims/PRSFX- Crunch.wav'],
    'Malicious Moonsault': ['music/battle_anims/PRSFX- Hyperspace Fury1.wav', 'music/battle_anims/PRSFX- Hyperspace Fury2.wav'],
    'Max Darkness': ['music/battle_anims/PRSFX- Black Hole Eclipse1.wav', 'music/battle_anims/PRSFX- Black Hole Eclipse2.wav', 'music/battle_anims/PRSFX- Black Hole Eclipse3.wav', 'music/battle_anims/PRSFX- Black Hole Eclipse4.wav'],
    'Wicked Blow': ['music/battle_anims/PRSFX- Crunch.wav'],
    'Wicked Torque': ['music/battle_anims/PRSFX- Crunch.wav'],
    'Baddy Bad': ['music/battle_anims/PRSFX- Dark Pulse1.wav', 'music/battle_anims/PRSFX- Dark Pulse2.wav'],
    'Fiery Wrath': ['music/battle_anims/PRSFX- Night Daze1.wav', 'music/battle_anims/PRSFX- Night Daze2.wav'],
    'Hidden Power Dark': ['music/battle_anims/PRSFX- Snarl.wav'],
    'Ruination': ['music/battle_anims/PRSFX- Snarl.wav'],
    'Obstruct': ['music/battle_anims/PRSFX- Dark Void.wav'],
    'Breaking Swipe': ['music/battle_anims/PRSFX- Dragon Tail.wav'],
    'Dragon Darts': ['music/battle_anims/PRSFX- Dragon Tail.wav'],
    'Dragon Hammer': ['music/battle_anims/PRSFX- Dragon Claw.wav'],
    'G-Max Depletion': ['music/battle_anims/PRSFX- Devastating Drake1.wav', 'music/battle_anims/PRSFX- Devastating Drake2.wav', 'music/battle_anims/PRSFX- Devastating Drake3.wav'],
    'Glaive Rush': ['music/battle_anims/PRSFX- Outrage1.wav', 'music/battle_anims/PRSFX- Outrage2.wav'],
    'Max Wyrmwind': ['music/battle_anims/PRSFX- Devastating Drake1.wav', 'music/battle_anims/PRSFX- Devastating Drake2.wav', 'music/battle_anims/PRSFX- Devastating Drake3.wav'],
    'Order Up': ['music/battle_anims/PRSFX- Dragon Claw.wav'],
    'Scale Shot': ['music/battle_anims/PRSFX- Dual Chop.wav'],
    'Clanging Scales': ['music/battle_anims/PRSFX- Spacial Rend.wav'],
    'Clangorous Soulblaze': ['music/battle_anims/PRSFX- Roar of Time.wav'],
    'Core Enforcer': ['music/battle_anims/PRSFX- Spacial Rend.wav'],
    'Dragon Energy': ['music/battle_anims/PRSFX- Roar of Time.wav'],
    'Dynamax Cannon': ['music/battle_anims/PRSFX- Spacial Rend.wav'],
    'Eternabeam': ['music/battle_anims/PRSFX- Roar of Time.wav'],
    'Fickle Beam': ['music/battle_anims/PRSFX- Dragon Pulse.wav'],
    'Hidden Power Dragon': ['music/battle_anims/PRSFX- Dragon Breath.wav'],
    'Nihil Light': ['music/battle_anims/PRSFX- Spacial Rend.wav'],
    'Clangorous Soul': ['music/battle_anims/PRSFX- Dragon Dance.wav'],
    'Dragon Cheer': ['music/battle_anims/PRSFX- Dragon Dance.wav'],
    'Aura Wheel': ['music/battle_anims/PRSFX- Fusion Bolt1.wav', 'music/battle_anims/PRSFX- Fusion Bolt2.wav'],
    'Bolt Beak': ['music/battle_anims/PRSFX- Wild Charge1.wav', 'music/battle_anims/PRSFX- Wild Charge2.wav'],
    'Double Shock': ['music/battle_anims/PRSFX- Volt Tackle1.wav', 'music/battle_anims/PRSFX- Volt Tackle2.wav'],
    'G-Max Stun Shock': ['music/battle_anims/PRSFX- Gigavolt Havoc1.wav', 'music/battle_anims/PRSFX- Gigavolt Havoc2.wav', 'music/battle_anims/PRSFX- Gigavolt Havoc3.wav'],
    'G-Max Volt Crash': ['music/battle_anims/PRSFX- Gigavolt Havoc1.wav', 'music/battle_anims/PRSFX- Gigavolt Havoc2.wav', 'music/battle_anims/PRSFX- Gigavolt Havoc3.wav'],
    'Max Lightning': ['music/battle_anims/PRSFX- Gigavolt Havoc1.wav', 'music/battle_anims/PRSFX- Gigavolt Havoc2.wav', 'music/battle_anims/PRSFX- Gigavolt Havoc3.wav'],
    'Supercell Slam': ['music/battle_anims/PRSFX- Fusion Bolt1.wav', 'music/battle_anims/PRSFX- Fusion Bolt2.wav'],
    'Zippy Zap': ['music/battle_anims/PRSFX- Zing Zap1.wav', 'music/battle_anims/PRSFX- Zing Zap2.wav', 'music/battle_anims/PRSFX- Zing Zap3.wav', 'music/battle_anims/PRSFX- Zing Zap4.wav'],
    '10,000,000 Volt Thunderbolt': ['music/battle_anims/PRSFX- Zap Cannon1.wav', 'music/battle_anims/PRSFX- Zap Cannon2.wav', 'music/battle_anims/PRSFX- Zap Cannon3.wav'],
    'Buzzy Buzz': ['music/battle_anims/PRSFX- Shockwave.wav'],
    'Electro Drift': ['music/battle_anims/PRSFX- Thunder.wav'],
    'Electro Shot': ['music/battle_anims/PRSFX- Zap Cannon1.wav', 'music/battle_anims/PRSFX- Zap Cannon2.wav', 'music/battle_anims/PRSFX- Zap Cannon3.wav'],
    'Hidden Power Electric': ['music/battle_anims/PRSFX- Shockwave.wav'],
    'Overdrive': ['music/battle_anims/PRSFX- Discharge.wav'],
    'Pika Papow': ['music/battle_anims/PRSFX- Electro Ball1.wav', 'music/battle_anims/PRSFX- Electro Ball2.wav'],
    'Rising Voltage': ['music/battle_anims/PRSFX- Volt Switch1.wav', 'music/battle_anims/PRSFX- Volt Switch2.wav'],
    'Stoked Sparksurfer': ['music/battle_anims/PRSFX- Zap Cannon1.wav', 'music/battle_anims/PRSFX- Zap Cannon2.wav', 'music/battle_anims/PRSFX- Zap Cannon3.wav'],
    'Thunder Cage': ['music/battle_anims/PRSFX- Discharge.wav'],
    'Thunderclap': ['music/battle_anims/PRSFX- Volt Switch1.wav', 'music/battle_anims/PRSFX- Volt Switch2.wav'],
    'Wildbolt Storm': ['music/battle_anims/PRSFX- Thunder.wav'],
    'G-Max Finale': ['music/battle_anims/PRSFX- Twinkle Tackle1.wav', 'music/battle_anims/PRSFX- Twinkle Tackle2.wav', 'music/battle_anims/PRSFX- Twinkle Tackle3.wav'],
    'G-Max Smite': ['music/battle_anims/PRSFX- Twinkle Tackle1.wav', 'music/battle_anims/PRSFX- Twinkle Tackle2.wav', 'music/battle_anims/PRSFX- Twinkle Tackle3.wav'],
    'Let\'s Snuggle Forever': ['music/battle_anims/PRSFX- Play Rough1.wav', 'music/battle_anims/PRSFX- Play Rough2.wav', 'music/battle_anims/PRSFX- Play Rough3.wav', 'music/battle_anims/PRSFX- Play Rough4.wav'],
    'Magical Torque': ['music/battle_anims/PRSFX- Play Rough1.wav', 'music/battle_anims/PRSFX- Play Rough2.wav', 'music/battle_anims/PRSFX- Play Rough3.wav', 'music/battle_anims/PRSFX- Play Rough4.wav'],
    'Max Starfall': ['music/battle_anims/PRSFX- Twinkle Tackle1.wav', 'music/battle_anims/PRSFX- Twinkle Tackle2.wav', 'music/battle_anims/PRSFX- Twinkle Tackle3.wav'],
    'Spirit Break': ['music/battle_anims/PRSFX- Play Rough1.wav', 'music/battle_anims/PRSFX- Play Rough2.wav', 'music/battle_anims/PRSFX- Play Rough3.wav', 'music/battle_anims/PRSFX- Play Rough4.wav'],
    'Alluring Voice': ['music/battle_anims/PRSFX- Dazzling Gleam.wav'],
    'Disarming Voice': ['music/battle_anims/PRSFX- Fairy Wind.wav'],
    'Fleur Cannon': ['music/battle_anims/PRSFX- Moonblast1.wav', 'music/battle_anims/PRSFX- Moonblast2.wav'],
    'Guardian of Alola': ['music/battle_anims/PRSFX- Natures Madness1.wav', 'music/battle_anims/PRSFX- Natures Madness2.wav'],
    'Light of Ruin': ['music/battle_anims/PRSFX- Moonblast1.wav', 'music/battle_anims/PRSFX- Moonblast2.wav'],
    'Misty Explosion': ['music/battle_anims/PRSFX- Moonblast1.wav', 'music/battle_anims/PRSFX- Moonblast2.wav'],
    'Sparkly Swirl': ['music/battle_anims/PRSFX- Moonblast1.wav', 'music/battle_anims/PRSFX- Moonblast2.wav'],
    'Springtide Storm': ['music/battle_anims/PRSFX- Moonblast1.wav', 'music/battle_anims/PRSFX- Moonblast2.wav'],
    'Strange Steam': ['music/battle_anims/PRSFX- Moonblast1.wav', 'music/battle_anims/PRSFX- Moonblast2.wav'],
    'Decorate': ['music/battle_anims/PRSFX- Aromatic Mist.wav'],
    'All-Out Pummeling': ['music/battle_anims/PRSFX- Counter1.wav', 'music/battle_anims/PRSFX- Counter2.wav'],
    'Axe Kick': ['music/battle_anims/PRSFX- Close Combat.wav'],
    'Body Press': ['music/battle_anims/PRSFX- Submission.wav'],
    'Collision Course': ['music/battle_anims/PRSFX- Cross Chop1.wav', 'music/battle_anims/PRSFX- Cross Chop2.wav'],
    'Combat Torque': ['music/battle_anims/PRSFX- Cross Chop1.wav', 'music/battle_anims/PRSFX- Cross Chop2.wav'],
    'G-Max Chi Strike': ['music/battle_anims/PRSFX- Triple Kick.wav'],
    'Max Knuckle': ['music/battle_anims/PRSFX- Triple Kick.wav'],
    'Meteor Assault': ['music/battle_anims/PRSFX- Focus Punch1.wav', 'music/battle_anims/PRSFX- Focus Punch2.wav', 'music/battle_anims/PRSFX- Focus Punch3.wav'],
    'Thunderous Kick': ['music/battle_anims/PRSFX- Sacred Sword1.wav', 'music/battle_anims/PRSFX- Sacred Sword2.wav'],
    'Triple Arrows': ['music/battle_anims/PRSFX- Sacred Sword1.wav', 'music/battle_anims/PRSFX- Sacred Sword2.wav'],
    'Upper Hand': ['music/battle_anims/PRSFX- Low Sweep.wav'],
    'Hidden Power Fighting': ['music/battle_anims/PRSFX- Aura Sphere1.wav', 'music/battle_anims/PRSFX- Aura Sphere2.wav'],
    'Coaching': ['music/battle_anims/PRSFX- Bulk Up1.wav', 'music/battle_anims/PRSFX- Bulk Up2.wav'],
    'No Retreat': ['music/battle_anims/PRSFX- Bulk Up1.wav', 'music/battle_anims/PRSFX- Bulk Up2.wav'],
    'Octolock': ['music/battle_anims/PRSFX- Bulk Up1.wav', 'music/battle_anims/PRSFX- Bulk Up2.wav'],
    'Victory Dance': ['music/battle_anims/PRSFX- Bulk Up1.wav', 'music/battle_anims/PRSFX- Bulk Up2.wav'],
    'Bitter Blade': ['music/battle_anims/PRSFX- Blaze Kick1.wav', 'music/battle_anims/PRSFX- Blaze Kick2.wav'],
    'Blazing Torque': ['music/battle_anims/PRSFX- Fire Lash1.wav', 'music/battle_anims/PRSFX- Fire Lash2.wav', 'music/battle_anims/PRSFX- Fire Lash3.wav', 'music/battle_anims/PRSFX- Fire Lash4.wav'],
    'G-Max Centiferno': ['music/battle_anims/PRSFX- Inferno Overdrive1.wav', 'music/battle_anims/PRSFX- Inferno Overdrive2.wav', 'music/battle_anims/PRSFX- Inferno Overdrive3.wav', 'music/battle_anims/PRSFX- Inferno Overdrive4.wav', 'music/battle_anims/PRSFX- Inferno Overdrive5.wav'],
    'G-Max Fireball': ['music/battle_anims/PRSFX- V-Create1.wav', 'music/battle_anims/PRSFX- V-Create2.wav'],
    'G-Max Wildfire': ['music/battle_anims/PRSFX- Inferno Overdrive1.wav', 'music/battle_anims/PRSFX- Inferno Overdrive2.wav', 'music/battle_anims/PRSFX- Inferno Overdrive3.wav', 'music/battle_anims/PRSFX- Inferno Overdrive4.wav', 'music/battle_anims/PRSFX- Inferno Overdrive5.wav'],
    'Max Flare': ['music/battle_anims/PRSFX- Sacred Fire1.wav', 'music/battle_anims/PRSFX- Sacred Fire2.wav'],
    'Pyro Ball': ['music/battle_anims/PRSFX- Flare Blitz1.wav', 'music/battle_anims/PRSFX- Flare Blitz2.wav', 'music/battle_anims/PRSFX- Flare Blitz3.wav'],
    'Raging Fury': ['music/battle_anims/PRSFX- Flare Blitz1.wav', 'music/battle_anims/PRSFX- Flare Blitz2.wav', 'music/battle_anims/PRSFX- Flare Blitz3.wav'],
    'Sizzly Slide': ['music/battle_anims/PRSFX- Flame Wheel1.wav', 'music/battle_anims/PRSFX- Flame Wheel2.wav'],
    'Temper Flare': ['music/battle_anims/PRSFX- Fire Punch1.wav', 'music/battle_anims/PRSFX- Fire Punch2.wav', 'music/battle_anims/PRSFX- Fire Punch3.wav'],
    'Armor Cannon': ['music/battle_anims/PRSFX- Blue Flare1.wav', 'music/battle_anims/PRSFX- Blue Flare2.wav'],
    'Burning Jealousy': ['music/battle_anims/PRSFX- Flame Burst.wav'],
    'Hidden Power Fire': ['music/battle_anims/PRSFX- Incinerate1.wav', 'music/battle_anims/PRSFX- Incinerate2.wav'],
    'Polar Flare': ['music/battle_anims/PRSFX- Mystical Fire1.wav', 'music/battle_anims/PRSFX- Mystical Fire2.wav'],
    'Torch Song': ['music/battle_anims/PRSFX- Fiery Dance1.wav', 'music/battle_anims/PRSFX- Fiery Dance2.wav'],
    'Burning Bulwark': ['music/battle_anims/PRSFX- Sunny Day.wav'],
    'Dual Wingbeat': ['music/battle_anims/PRSFX- Peck.wav'],
    'Floaty Fall': ['music/battle_anims/PRSFX- Fly1.wav', 'music/battle_anims/PRSFX- Fly2.wav'],
    'G-Max Wind Rage': ['music/battle_anims/PRSFX- Peck.wav'],
    'Max Airstream': ['music/battle_anims/PRSFX- Peck.wav'],
    'Supersonic Skystrike': ['music/battle_anims/PRSFX- Peck.wav'],
    'Bleakwind Storm': ['music/battle_anims/PRSFX- Aeroblast.wav'],
    'Hidden Power Flying': ['music/battle_anims/PRSFX- Air Cutter1.wav', 'music/battle_anims/PRSFX- Air Cutter2.wav'],
    'Mirror Move': ['music/battle_anims/PRSFX- Defog.wav'],
    'G-Max Terror': ['music/battle_anims/PRSFX- Astonish1.wav', 'music/battle_anims/PRSFX- Astonish2.wav'],
    'Last Respects': ['music/battle_anims/PRSFX- Shadow Punch1.wav', 'music/battle_anims/PRSFX- Shadow Punch2.wav'],
    'Max Phantasm': ['music/battle_anims/PRSFX- Astonish1.wav', 'music/battle_anims/PRSFX- Astonish2.wav'],
    'Never-Ending Nightmare': ['music/battle_anims/PRSFX- Astonish1.wav', 'music/battle_anims/PRSFX- Astonish2.wav'],
    'Poltergeist': ['music/battle_anims/PRSFX- Shadow Force1.wav', 'music/battle_anims/PRSFX- Shadow Force2.wav'],
    'Rage Fist': ['music/battle_anims/PRSFX- Shadow Punch1.wav', 'music/battle_anims/PRSFX- Shadow Punch2.wav'],
    'Shadow Strike': ['music/battle_anims/PRSFX- Spirit Shackle1.wav', 'music/battle_anims/PRSFX- Spirit Shackle2.wav', 'music/battle_anims/PRSFX- Spirit Shackle3.wav', 'music/battle_anims/PRSFX- Spirit Shackle4.wav'],
    'Sinister Arrow Raid': ['music/battle_anims/PRSFX- Shadow Force1.wav', 'music/battle_anims/PRSFX- Shadow Force2.wav'],
    'Soul-Stealing 7-Star Strike': ['music/battle_anims/PRSFX- Shadow Force1.wav', 'music/battle_anims/PRSFX- Shadow Force2.wav'],
    'Astral Barrage': ['music/battle_anims/PRSFX- Shadow Ball1.wav', 'music/battle_anims/PRSFX- Shadow Ball2.wav'],
    'Bitter Malice': ['music/battle_anims/PRSFX- Shadow Ball1.wav', 'music/battle_anims/PRSFX- Shadow Ball2.wav'],
    'Hidden Power Ghost': ['music/battle_anims/PRSFX- Ominous Wind.wav'],
    'Infernal Parade': ['music/battle_anims/PRSFX- Ominous Wind.wav'],
    'Menacing Moonraze Maelstrom': ['music/battle_anims/PRSFX- Shadow Ball1.wav', 'music/battle_anims/PRSFX- Shadow Ball2.wav'],
    'Moongeist Beam': ['music/battle_anims/PRSFX- Shadow Ball1.wav', 'music/battle_anims/PRSFX- Shadow Ball2.wav'],
    'Branch Poke': ['music/battle_anims/PRSFX- Leafage 1.wav', 'music/battle_anims/PRSFX- Leafage 2.wav'],
    'Drum Beating': ['music/battle_anims/PRSFX- Seed Bomb1.wav', 'music/battle_anims/PRSFX- Seed Bomb2.wav'],
    'Flower Trick': ['music/battle_anims/PRSFX- Trop Kick1.wav', 'music/battle_anims/PRSFX- Trop Kick2.wav', 'music/battle_anims/PRSFX- Trop Kick3.wav'],
    'G-Max Drum Solo': ['music/battle_anims/PRSFX- Power Whip.wav'],
    'G-Max Sweetness': ['music/battle_anims/PRSFX- Bloom Doom1.wav', 'music/battle_anims/PRSFX- Bloom Doom2.wav', 'music/battle_anims/PRSFX- Bloom Doom3.wav'],
    'G-Max Tartness': ['music/battle_anims/PRSFX- Bloom Doom1.wav', 'music/battle_anims/PRSFX- Bloom Doom2.wav', 'music/battle_anims/PRSFX- Bloom Doom3.wav'],
    'G-Max Vine Lash': ['music/battle_anims/PRSFX- Bloom Doom1.wav', 'music/battle_anims/PRSFX- Bloom Doom2.wav', 'music/battle_anims/PRSFX- Bloom Doom3.wav'],
    'Grassy Glide': ['music/battle_anims/PRSFX- Razor Leaf1.wav', 'music/battle_anims/PRSFX- Razor Leaf2.wav'],
    'Grav Apple': ['music/battle_anims/PRSFX- Seed Bomb1.wav', 'music/battle_anims/PRSFX- Seed Bomb2.wav'],
    'Ivy Cudgel': ['music/battle_anims/PRSFX- Leaf Blade.wav'],
    'Max Overgrowth': ['music/battle_anims/PRSFX- Bloom Doom1.wav', 'music/battle_anims/PRSFX- Bloom Doom2.wav', 'music/battle_anims/PRSFX- Bloom Doom3.wav'],
    'Sappy Seed': ['music/battle_anims/PRSFX- Leaf Blade.wav'],
    'Snap Trap': ['music/battle_anims/PRSFX- Leafage 1.wav', 'music/battle_anims/PRSFX- Leafage 2.wav'],
    'Solar Blade': ['music/battle_anims/PRSFX- Power Whip.wav'],
    'Trailblaze': ['music/battle_anims/PRSFX- Razor Leaf1.wav', 'music/battle_anims/PRSFX- Razor Leaf2.wav'],
    'Apple Acid': ['music/battle_anims/PRSFX- Grass Pledge1.wav', 'music/battle_anims/PRSFX- Grass Pledge2.wav'],
    'Chloroblast': ['music/battle_anims/PRSFX- Frenzy Plant1.wav', 'music/battle_anims/PRSFX- Frenzy Plant2.wav'],
    'Hidden Power Grass': ['music/battle_anims/PRSFX- Magical Leaf1.wav', 'music/battle_anims/PRSFX- Magical Leaf2.wav'],
    'Matcha Gotcha': ['music/battle_anims/PRSFX- Grass Pledge1.wav', 'music/battle_anims/PRSFX- Grass Pledge2.wav'],
    'Syrup Bomb': ['music/battle_anims/PRSFX- Magical Leaf1.wav', 'music/battle_anims/PRSFX- Magical Leaf2.wav'],
    'Jungle Healing': ['music/battle_anims/PRSFX- Aromatherapy.wav'],
    'Spicy Extract': ['music/battle_anims/PRSFX- Aromatherapy.wav'],
    'G-Max Sandblast': ['music/battle_anims/PRSFX- Fissure.wav'],
    'Headlong Rush': ['music/battle_anims/PRSFX- Precipice Blades.wav'],
    'Max Quake': ['music/battle_anims/PRSFX- Fissure.wav'],
    'Tectonic Rage': ['music/battle_anims/PRSFX- Fissure.wav'],
    'Hidden Power Ground': ['music/battle_anims/PRSFX- Mud Bomb1.wav', 'music/battle_anims/PRSFX- Mud Bomb2.wav'],
    'Sandsear Storm': ['music/battle_anims/PRSFX- Earth Power.wav'],
    'Scorching Sands': ['music/battle_anims/PRSFX- Mud Bomb1.wav', 'music/battle_anims/PRSFX- Mud Bomb2.wav'],
    'G-Max Resonance': ['music/battle_anims/PRSFX- Subzero Slammer1.wav', 'music/battle_anims/PRSFX- Subzero Slammer2.wav', 'music/battle_anims/PRSFX- Subzero Slammer3.wav', 'music/battle_anims/PRSFX- Subzero Slammer4.wav'],
    'Glacial Lance': ['music/battle_anims/PRSFX- Freeze Shock1.wav', 'music/battle_anims/PRSFX- Freeze Shock2.wav', 'music/battle_anims/PRSFX- Freeze Shock3.wav'],
    'Ice Spinner': ['music/battle_anims/PRSFX- Ice Punch1.wav', 'music/battle_anims/PRSFX- Ice Punch2.wav'],
    'Max Hailstorm': ['music/battle_anims/PRSFX- Subzero Slammer1.wav', 'music/battle_anims/PRSFX- Subzero Slammer2.wav', 'music/battle_anims/PRSFX- Subzero Slammer3.wav', 'music/battle_anims/PRSFX- Subzero Slammer4.wav'],
    'Mountain Gale': ['music/battle_anims/PRSFX- Ice Hammer1.wav', 'music/battle_anims/PRSFX- Ice Hammer2.wav'],
    'Triple Axel': ['music/battle_anims/PRSFX- Icicle Spear.wav'],
    'Freezy Frost': ['music/battle_anims/PRSFX- Blizzard.wav'],
    'Hidden Power Ice': ['music/battle_anims/PRSFX- Frost Breath1.wav', 'music/battle_anims/PRSFX- Frost Breath2.wav'],
    'Chilly Reception': ['music/battle_anims/PRSFX- Aurora Veil1.wav', 'music/battle_anims/PRSFX- Aurora Veil2.wav', 'music/battle_anims/PRSFX- Aurora Veil3.wav', 'music/battle_anims/PRSFX- Aurora Veil4.wav'],
    'Snowscape': ['music/battle_anims/PRSFX- Aurora Veil1.wav', 'music/battle_anims/PRSFX- Aurora Veil2.wav', 'music/battle_anims/PRSFX- Aurora Veil3.wav', 'music/battle_anims/PRSFX- Aurora Veil4.wav'],
    'Breakneck Blitz': ['music/battle_anims/PRSFX- Bide1.wav', 'music/battle_anims/PRSFX- Bide2.wav'],
    'G-Max Cuddle': ['music/battle_anims/PRSFX- Constrict.wav'],
    'G-Max Gold Rush': ['music/battle_anims/PRSFX- Constrict.wav'],
    'G-Max Replenish': ['music/battle_anims/PRSFX- Constrict.wav'],
    'Hold Back': ['music/battle_anims/PRSFX- Fake Out1.wav', 'music/battle_anims/PRSFX- Fake Out2.wav'],
    'Hyper Drill': ['music/battle_anims/PRSFX- Egg Bomb1.wav', 'music/battle_anims/PRSFX- Egg Bomb2.wav'],
    'Max Strike': ['music/battle_anims/PRSFX- Constrict.wav'],
    'Population Bomb': ['music/battle_anims/PRSFX- Rage1.wav', 'music/battle_anims/PRSFX- Rage2.wav'],
    'Raging Bull': ['music/battle_anims/PRSFX- Rock Climb.wav'],
    'Secret Power': ['music/battle_anims/PRSFX- Chip Away.wav'],
    'Veevee Volley': ['music/battle_anims/PRSFX- Bide1.wav', 'music/battle_anims/PRSFX- Bide2.wav'],
    'Blood Moon': ['music/battle_anims/PRSFX- Boomburst.wav'],
    'Hyper Voice': ['music/battle_anims/PRSFX- Uproar1.wav', 'music/battle_anims/PRSFX- Uproar2.wav'],
    'Revelation Dance': ['music/battle_anims/PRSFX- Uproar1.wav', 'music/battle_anims/PRSFX- Uproar2.wav'],
    'Tera Blast': ['music/battle_anims/PRSFX- Razor Wind1.wav', 'music/battle_anims/PRSFX- Razor Wind2.wav'],
    'Tera Starstorm': ['music/battle_anims/PRSFX- Techno Blast 1.wav', 'music/battle_anims/PRSFX- Techno Blast 2.wav', 'music/battle_anims/PRSFX- Techno Blast 3.wav'],
    'Terrain Pulse': ['music/battle_anims/PRSFX- Snore.wav'],
    'Celebrate': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Conversion 2': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Copycat': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Court Change': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Doodle': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Fillet Away': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Growl': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Happy Hour': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Hold Hands': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Howl': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Max Guard': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Nature Power': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Power Shift': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Revival Blessing': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Shed Tail': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Stuff Cheeks': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Teatime': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Tidy Up': ['music/battle_anims/PRSFX- Acupressure1.wav', 'music/battle_anims/PRSFX- Acupressure2.wav'],
    'Acid Downpour': ['music/battle_anims/PRSFX- Poison Sting.wav'],
    'Barb Barrage': ['music/battle_anims/PRSFX- Cross Poison1.wav', 'music/battle_anims/PRSFX- Cross Poison2.wav'],
    'Dire Claw': ['music/battle_anims/PRSFX- Poison Jab1.wav', 'music/battle_anims/PRSFX- Poison Jab2.wav'],
    'G-Max Malodor': ['music/battle_anims/PRSFX- Poison Sting.wav'],
    'Max Ooze': ['music/battle_anims/PRSFX- Poison Sting.wav'],
    'Mortal Spin': ['music/battle_anims/PRSFX- Poison Sting.wav'],
    'Noxious Torque': ['music/battle_anims/PRSFX- Gunk Shot.wav'],
    'Hidden Power Poison': ['music/battle_anims/PRSFX- Sludge.wav'],
    'Malignant Chain': ['music/battle_anims/PRSFX- Sludge Wave.wav'],
    'Shell Side Arm': ['music/battle_anims/PRSFX- Sludge Bomb1.wav', 'music/battle_anims/PRSFX- Sludge Bomb2.wav'],
    'Corrosive Gas': ['music/battle_anims/PRSFX- Acid Armor1.wav', 'music/battle_anims/PRSFX- Acid Armor2.wav'],
    'G-Max Gravitas': ['music/battle_anims/PRSFX- Shattered Psyche1.wav', 'music/battle_anims/PRSFX- Shattered Psyche2.wav', 'music/battle_anims/PRSFX- Shattered Psyche3.wav'],
    'Max Mindstorm': ['music/battle_anims/PRSFX- Shattered Psyche1.wav', 'music/battle_anims/PRSFX- Shattered Psyche2.wav', 'music/battle_anims/PRSFX- Shattered Psyche3.wav'],
    'Psyblade': ['music/battle_anims/PRSFX- Zen Headbutt1.wav', 'music/battle_anims/PRSFX- Zen Headbutt2.wav'],
    'Psychic Fangs': ['music/battle_anims/PRSFX- Zen Headbutt1.wav', 'music/battle_anims/PRSFX- Zen Headbutt2.wav'],
    'Psyshield Bash': ['music/battle_anims/PRSFX- Psycho Cut.wav'],
    'Eerie Spell': ['music/battle_anims/PRSFX- Extrasensory.wav'],
    'Esper Wing': ['music/battle_anims/PRSFX- Extrasensory.wav'],
    'Expanding Force': ['music/battle_anims/PRSFX- Extrasensory.wav'],
    'Freezing Glare': ['music/battle_anims/PRSFX- Psychic.wav'],
    'Genesis Supernova': ['music/battle_anims/PRSFX- Prismatic Laser1.wav', 'music/battle_anims/PRSFX- Prismatic Laser2.wav', 'music/battle_anims/PRSFX- Prismatic Laser3.wav'],
    'Glitzy Glow': ['music/battle_anims/PRSFX- Extrasensory.wav'],
    'Hidden Power Psychic': ['music/battle_anims/PRSFX- Psybeam.wav'],
    'Light That Burns the Sky': ['music/battle_anims/PRSFX- Prismatic Laser1.wav', 'music/battle_anims/PRSFX- Prismatic Laser2.wav', 'music/battle_anims/PRSFX- Prismatic Laser3.wav'],
    'Lumina Crash': ['music/battle_anims/PRSFX- Extrasensory.wav'],
    'Mystical Power': ['music/battle_anims/PRSFX- Psybeam.wav'],
    'Psychic Noise': ['music/battle_anims/PRSFX- Extrasensory.wav'],
    'Twin Beam': ['music/battle_anims/PRSFX- Confusion.wav'],
    'Heal Pulse': ['music/battle_anims/PRSFX- Agility.wav'],
    'Lunar Blessing': ['music/battle_anims/PRSFX- Agility.wav'],
    'Magic Powder': ['music/battle_anims/PRSFX- Agility.wav'],
    'Rest': ['music/battle_anims/PRSFX- Agility.wav'],
    'Take Heart': ['music/battle_anims/PRSFX- Agility.wav'],
    'Continental Crush': ['music/battle_anims/PRSFX- Rock Blast.wav'],
    'G-Max Volcalith': ['music/battle_anims/PRSFX- Rock Blast.wav'],
    'Max Rockfall': ['music/battle_anims/PRSFX- Rock Blast.wav'],
    'Mighty Cleave': ['music/battle_anims/PRSFX- Diamond Storm1.wav', 'music/battle_anims/PRSFX- Diamond Storm2.wav'],
    'Salt Cure': ['music/battle_anims/PRSFX- Accelerock1.wav', 'music/battle_anims/PRSFX- Accelerock2.wav', 'music/battle_anims/PRSFX- Accelerock3.wav'],
    'Splintered Stormshards': ['music/battle_anims/PRSFX- Head Smash.wav'],
    'Stone Axe': ['music/battle_anims/PRSFX- Rock Tomb.wav'],
    'Hidden Power Rock': ['music/battle_anims/PRSFX- Ancient Power1.wav', 'music/battle_anims/PRSFX- Ancient Power2.wav'],
    'Meteor Beam': ['music/battle_anims/PRSFX- Power Gem1.wav'],
    'Paleo Wave': ['music/battle_anims/PRSFX- Power Gem1.wav'],
    'Tar Shot': ['music/battle_anims/PRSFX- Rock Polish.wav'],
    'Behemoth Bash': ['music/battle_anims/PRSFX- Iron Tail1.wav', 'music/battle_anims/PRSFX- Iron Tail2.wav'],
    'Behemoth Blade': ['music/battle_anims/PRSFX- Iron Tail1.wav', 'music/battle_anims/PRSFX- Iron Tail2.wav'],
    'Corkscrew Crash': ['music/battle_anims/PRSFX- Gyro Ball1.wav', 'music/battle_anims/PRSFX- Gyro Ball2.wav'],
    'Double Iron Bash': ['music/battle_anims/PRSFX- Magnet Bomb1.wav', 'music/battle_anims/PRSFX- Magnet Bomb2.wav'],
    'G-Max Meltdown': ['music/battle_anims/PRSFX- Gyro Ball1.wav', 'music/battle_anims/PRSFX- Gyro Ball2.wav'],
    'G-Max Steelsurge': ['music/battle_anims/PRSFX- Gyro Ball1.wav', 'music/battle_anims/PRSFX- Gyro Ball2.wav'],
    'Gigaton Hammer': ['music/battle_anims/PRSFX- Iron Tail1.wav', 'music/battle_anims/PRSFX- Iron Tail2.wav'],
    'Hard Press': ['music/battle_anims/PRSFX- Gyro Ball1.wav', 'music/battle_anims/PRSFX- Gyro Ball2.wav'],
    'Max Steelspike': ['music/battle_anims/PRSFX- Gyro Ball1.wav', 'music/battle_anims/PRSFX- Gyro Ball2.wav'],
    'Searing Sunraze Smash': ['music/battle_anims/PRSFX- Iron Tail1.wav', 'music/battle_anims/PRSFX- Iron Tail2.wav'],
    'Spin Out': ['music/battle_anims/PRSFX- Iron Tail1.wav', 'music/battle_anims/PRSFX- Iron Tail2.wav'],
    'Steel Roller': ['music/battle_anims/PRSFX- Iron Tail1.wav', 'music/battle_anims/PRSFX- Iron Tail2.wav'],
    'Sunsteel Strike': ['music/battle_anims/PRSFX- Iron Tail1.wav', 'music/battle_anims/PRSFX- Iron Tail2.wav'],
    'Hidden Power Steel': ['music/battle_anims/PRSFX- Mirror Shot.wav'],
    'Make It Rain': ['music/battle_anims/PRSFX- Doom Desire1.wav', 'music/battle_anims/PRSFX- Doom Desire2.wav'],
    'Steel Beam': ['music/battle_anims/PRSFX- Doom Desire1.wav', 'music/battle_anims/PRSFX- Doom Desire2.wav'],
    'Tachyon Cutter': ['music/battle_anims/PRSFX- Mirror Shot.wav'],
    'Shelter': ['music/battle_anims/PRSFX- Autotomize.wav', 'music/battle_anims/PRSFX- Autotomize1.m4a', 'music/battle_anims/PRSFX- Autotomize2.wav'],
    'Aqua Cutter': ['music/battle_anims/PRSFX- Razor Shell.wav'],
    'Aqua Step': ['music/battle_anims/PRSFX- Dive1.wav', 'music/battle_anims/PRSFX- Dive2.wav', 'music/battle_anims/PRSFX- Dive3.wav'],
    'Fishious Rend': ['music/battle_anims/PRSFX- Liquidation1.wav', 'music/battle_anims/PRSFX- Liquidation2.wav', 'music/battle_anims/PRSFX- Liquidation3.wav', 'music/battle_anims/PRSFX- Liquidation4.wav'],
    'Flip Turn': ['music/battle_anims/PRSFX- Razor Shell.wav'],
    'G-Max Cannonade': ['music/battle_anims/PRSFX- Hydro Vortex1.wav', 'music/battle_anims/PRSFX- Hydro Vortex2.wav', 'music/battle_anims/PRSFX- Hydro Vortex3.wav'],
    'G-Max Foam Burst': ['music/battle_anims/PRSFX- Hydro Vortex1.wav', 'music/battle_anims/PRSFX- Hydro Vortex2.wav', 'music/battle_anims/PRSFX- Hydro Vortex3.wav'],
    'G-Max Hydrosnipe': ['music/battle_anims/PRSFX- Crabhammer.wav'],
    'G-Max Rapid Flow': ['music/battle_anims/PRSFX- Hydro Vortex1.wav', 'music/battle_anims/PRSFX- Hydro Vortex2.wav', 'music/battle_anims/PRSFX- Hydro Vortex3.wav'],
    'G-Max Stonesurge': ['music/battle_anims/PRSFX- Hydro Vortex1.wav', 'music/battle_anims/PRSFX- Hydro Vortex2.wav', 'music/battle_anims/PRSFX- Hydro Vortex3.wav'],
    'Jet Punch': ['music/battle_anims/PRSFX- Razor Shell.wav'],
    'Max Geyser': ['music/battle_anims/PRSFX- Hydro Vortex1.wav', 'music/battle_anims/PRSFX- Hydro Vortex2.wav', 'music/battle_anims/PRSFX- Hydro Vortex3.wav'],
    'Surging Strikes': ['music/battle_anims/PRSFX- Clamp1.wav', 'music/battle_anims/PRSFX- Clamp2.wav', 'music/battle_anims/PRSFX- Clamp3.wav'],
    'Triple Dive': ['music/battle_anims/PRSFX- Clamp1.wav', 'music/battle_anims/PRSFX- Clamp2.wav', 'music/battle_anims/PRSFX- Clamp3.wav'],
    'Wave Crash': ['music/battle_anims/PRSFX- Crabhammer.wav'],
    'Bouncy Bubble': ['music/battle_anims/PRSFX- Water Pulse.wav', 'music/battle_anims/PRSFX- Water Pulse2.wav'],
    'Chilling Water': ['music/battle_anims/PRSFX- Bubble.wav'],
    'Hidden Power Water': ['music/battle_anims/PRSFX- Water Pulse.wav', 'music/battle_anims/PRSFX- Water Pulse2.wav'],
    'Hydro Steam': ['music/battle_anims/PRSFX- Scald1.wav', 'music/battle_anims/PRSFX- Scald2.wav'],
    'Snipe Shot': ['music/battle_anims/PRSFX- Scald1.wav', 'music/battle_anims/PRSFX- Scald2.wav'],
    'Splishy Splash': ['music/battle_anims/PRSFX- Muddy Water.wav'],
    'Life Dew': ['music/battle_anims/PRSFX- Aqua Ring1.wav', 'music/battle_anims/PRSFX- Aqua Ring2.wav'],
};
