// Story-mode power-curve report (balance instrumentation).
//
// Boots battle.html headlessly, walks STORY_EVENTS_RAW, and for every battle
// event rolls the enemy team through the live pipeline (rollTrainerTeam ->
// buildPokemon -> league boost -> foe difficulty scaling) and scores it with
// estimateMonPower. It also models two reference player teams at the same
// progress (see window.StoryMode.powerCurveReport): an "equal-footing" player
// drawn from the same grade pool as the enemy and a "realistic" player drawn
// from the weaker wild grade curve, both teched to the contemporary professor
// build tier.
//
// Output: tests/reports/power-curve.md (a Markdown table + summary) and a
// console dump. This is the golden-master ruler for the balance work — run it
// before and after any tuning change to see the curve move.
//
//   node tests/audit/power-curve.mjs [--difficulty=normal] [--trials=8] [--gens=1,2,3,4,5,6,7,8,9]

import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { loadEngine } from '../helpers/load-engine.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(__dirname, '..', 'reports');
const OUT_MD = join(OUT_DIR, 'power-curve.md');

function parseArgs(argv) {
  const o = { difficulty: 'normal', trials: 8, gens: [1, 2, 3, 4, 5, 6, 7, 8, 9] };
  for (const a of argv.slice(2)) {
    const m = /^--([^=]+)=(.*)$/.exec(a);
    if (!m) continue;
    const [, k, v] = m;
    if (k === 'difficulty') o.difficulty = v;
    else if (k === 'trials') o.trials = Math.max(1, parseInt(v, 10) || 8);
    else if (k === 'gens') o.gens = v.split(',').map(n => parseInt(n, 10)).filter(Boolean);
  }
  return o;
}

// Provisional "intended band" thresholds (challenge ratio = enemy / realistic
// player). These are starting flags, not a verdict — the whole point of the
// report is to calibrate them against the real curve.
const WALL_RATIO = 1.6;       // enemy >1.6x a realistic player -> likely wall
const STEAMROLL_RATIO = 0.6;  // enemy <0.6x -> likely free win

function fmt(x) { return (x == null) ? '' : String(x); }

function toMarkdown(rows, opts) {
  const lines = [];
  lines.push('# Story-mode power curve');
  lines.push('');
  lines.push('_Generated by `tests/audit/power-curve.mjs`. Do not hand-edit._');
  lines.push('');
  lines.push(`- difficulty: **${opts.difficulty}**`);
  lines.push(`- gens: **${opts.gens.join(',')}**`);
  lines.push(`- trials per row: **${opts.trials}**`);
  lines.push('');
  lines.push('Power is a unitless Lv50 proxy (`estimateMonPower`): a typical mid-game');
  lines.push('fully-evolved attacker scores ~100 per mon. Columns:');
  lines.push('');
  lines.push('- **enemy** — mean total power of the rolled enemy team (post grade roll, build-tier');
  lines.push('  degrade, IV/EV tier, item, league boost and foe stat multiplier).');
  lines.push('- **pEqual** — reference player drawn from the *same* grade pool as the enemy,');
  lines.push('  teched to the contemporary professor build tier (isolates the enemy build/mult dials).');
  lines.push('- **pReal** — reference player drawn from the weaker *wild* grade curve, same tier');
  lines.push('  (a realistic "kept-up but catches what the routes offer" player).');
  lines.push('- **e/eq**, **e/real** — challenge ratios (enemy / player). ~1.0 = even.');
  lines.push('');
  lines.push('| row | event | bdg | party | tier | enemy | pEqual | pReal | e/eq | e/real | flag |');
  lines.push('|----:|-------|----:|------:|-----:|------:|-------:|------:|-----:|-------:|------|');
  for (const r of rows) {
    let flag = '';
    if (r.error) flag = 'ERR';
    else if (r.ratioReal >= WALL_RATIO) flag = 'WALL';
    else if (r.ratioReal && r.ratioReal <= STEAMROLL_RATIO) flag = 'easy';
    lines.push(`| ${fmt(r.row)} | ${fmt(r.event)} | ${fmt(r.badges)} | ${fmt(r.partySize)} | ${fmt(r.playerTier)} | ${fmt(r.enemyPower)} | ${fmt(r.playerEqual)} | ${fmt(r.playerReal)} | ${fmt(r.ratioEqual)} | ${fmt(r.ratioReal)} | ${flag} |`);
  }
  lines.push('');
  const errs = rows.filter(r => r.error);
  const walls = rows.filter(r => !r.error && r.ratioReal >= WALL_RATIO);
  const easies = rows.filter(r => !r.error && r.ratioReal && r.ratioReal <= STEAMROLL_RATIO);
  lines.push('## Summary');
  lines.push('');
  lines.push(`- battle events scored: **${rows.length}**`);
  lines.push(`- **roll ERRORS (enemy team failed to roll): ${errs.length}**${errs.length ? ' — rows ' + errs.map(r => r.row).join(', ') : ''}`);
  lines.push(`- flagged WALL (enemy/real >= ${WALL_RATIO}): **${walls.length}**${walls.length ? ' — rows ' + walls.map(r => r.row).join(', ') : ''}`);
  lines.push(`- flagged easy (enemy/real <= ${STEAMROLL_RATIO}): **${easies.length}**${easies.length ? ' — rows ' + easies.map(r => r.row).join(', ') : ''}`);
  lines.push('');
  lines.push('### Sample enemy teams (first trial per row)');
  lines.push('');
  for (const r of rows) lines.push(`- row ${r.row} (${r.event}, ${r.trainer}): ${r.sampleTeam}`);
  lines.push('');
  return lines.join('\n');
}

(async () => {
  const opts = parseArgs(process.argv);
  const t0 = Date.now();
  const { window, teardown } = await loadEngine();
  if (!window.StoryMode || typeof window.StoryMode.powerCurveReport !== 'function') {
    console.error('powerCurveReport not found on window.StoryMode — is battle.html up to date?');
    try { teardown(); } catch (e) {}
    process.exit(1);
  }
  const rows = window.StoryMode.powerCurveReport({ difficulty: opts.difficulty, gens: opts.gens, trials: opts.trials });
  try { mkdirSync(OUT_DIR, { recursive: true }); } catch (e) {}
  const md = toMarkdown(rows, opts);
  writeFileSync(OUT_MD, md, 'utf8');

  console.log(`\n[power-curve] ${rows.length} events in ${((Date.now() - t0) / 1000).toFixed(1)}s -> ${OUT_MD}`);
  for (const r of rows) {
    const flag = r.error ? '  <-- ERR' : (r.ratioReal >= WALL_RATIO ? '  <-- WALL' : (r.ratioReal && r.ratioReal <= STEAMROLL_RATIO ? '  <-- easy' : ''));
    console.log(
      `  row ${String(r.row).padStart(2)} ${String(r.event).padEnd(16)} bdg${r.badges} ps${r.partySize} T${r.playerTier}  ` +
      `enemy=${String(r.enemyPower).padStart(6)}  pEq=${String(r.playerEqual).padStart(6)}  pReal=${String(r.playerReal).padStart(6)}  ` +
      `e/eq=${String(r.ratioEqual).padStart(4)}  e/real=${String(r.ratioReal).padStart(4)}${flag}`
    );
  }
  try { teardown(); } catch (e) {}
  process.exit(0);
})().catch(err => {
  console.error('[power-curve] failed:', err);
  process.exit(1);
});
